version: '3.3'

services:
  cassandra-website:
    build: .
    image: cassandra-website:latest
    user: build
    volumes:
      - ./src:/home/build/cassandra-site/src
      - ./content:/home/build/cassandra-site/publish

  cassandra-website-serve:
    build: .
    image: cassandra-website:latest
    user: build
    entrypoint: /home/build/docker-entrypoint-jekyll-serve.sh
    ports:
      - 4000:4000
    volumes:
      - ./src:/home/build/cassandra-site/src
      - ./content:/home/build/cassandra-site/publish
      - ./docker-entrypoint-jekyll-serve.sh:/home/build/docker-entrypoint-jekyll-serve.sh

  preview:
    image: nginx
    ports:
      - "8000:80"
    volumes:
      - "./content:/usr/share/nginx/html"
    command: [nginx-debug, '-g', 'daemon off;']

