= Announcing Monthly Town Halls
:page-layout: single-post
:page-role: blog-post
:page-post-date: April 19, 2023
:page-post-author: The Apache Cassandra Community
:description: Announcement of monthly virtual town halls.
:keywords: 

As the Apache Cassandra® community grows, it is important that we have dedicated forums to gather, share, and learn. With this in mind, we are kicking off monthly live, virtual Town Hall meetings starting this month. **Our very first Town Hall is on April 26 at 9am PT, and https://www.meetup.com/cassandra-global/events/292858262/[you can register here^]**. We’ll also be hosting an “Ask Me Anything” (AMA) on https://discord.com/invite/Ut8YctQWac[Planet Cassandra Discord^] following the event.

### What to expect from Cassandra Town Halls

Our goal with Town Halls is to provide a forum for users of Cassandra to come together - whether you’re brand new or have been using it for years. During the meetings you can share what you’ve learned on your Cassandra journey and hear valuable lessons from your peers. You can expect project and release updates from community leaders, as well as  info about what’s coming for Cassandra, and guidance on how you can participate. 

Going forward, meetings are scheduled to be live-streamed on Zoom the **fourth Thursday of the month at 8am PT**. However, we want to find a time that works for most, so https://calendly.com/d/z2m-jps-68c/may-cassandra-town-hall-virtual-meeting[please take this poll^] to let us know what works best for you. We’ll do our best to adjust accordingly. We’ll also make recordings immediately available on https://www.youtube.com/@PlanetCassandra/streams[the Planet Cassandra YouTube channel^]. 

### Agenda for our first Town Hall

For our inaugural event, we are  excited that https://www.linkedin.com/in/rustyrazorblade/[Jon Haddad^] will share what Netflix has learned along their Cassandra journey. Project Management Committee lead, https://www.linkedin.com/in/josh-mckenzie-59b38b14/[Josh MacKenzie^] will also give a project update. There will be space to meet each other and ask questions.

### Join the post-Town Hall Discord AMA

Immediately after our Town Hall (April 26 at 10am PT), join our hosts and the community on the Planet Cassandra Discord for an AMA. This AMA is an extension of the Town Hall, offering more time and space for you to learn and engage. We’ll be there live until 11am PT,  but rest assured, if you’re not there live, we’ll be checking back frequently to answer questions async throughout the day.

### How to Join the Meeting

Ready to attend? Copy the invite from the public https://calendar.google.com/calendar/u/0?cid=a2w5cHVoZ2s3cXRkdXFhdHRlOHRmZDVtcHNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ[Cassandra Community Meeting Calendar^]. 

Hope to see you there! And as always, don’t be shy about sharing feedback on Town Halls. We want these to be useful for you, and your input is valuable.

* https://discord.gg/Ut8YctQWac[Planet Cassandra Discord^]
* https://www.youtube.com/@PlanetCassandra/streams[Planet Cassandra YouTube^] (for replays)
* https://bit.ly/3Aez8nx[ASF Slack #cassandra^]
* https://planetcassandra.org/[Planet Cassandra Website^]
