= Announcing Apache Cassandra® 5.0
:page-layout: single-post
:page-role: blog-post
:page-post-date: September 5, 2024
:page-post-author: The Apache Cassandra Community
:description: The Apache Cassandra Community
:keywords: 


The Cassandra project is happy to announce the general availability of Apache Cassandra® 5.0! This major release marks a significant milestone in the evolution of the world's most powerful distributed database used by over 30,000 organizations worldwide. This major release brings substantial improvements in performance, usability, and capabilities. In addition, there is significant new functionality specifically targeted for ease of use for both developers and operators.

## Key Features of Apache Cassandra® 5.0
1. *Storage Attached Indexes (SAI)*
SAI revolutionizes query flexibility and performance, especially for large datasets. It allows for more efficient querying on non-primary key columns, significantly expanding data modeling possibilities. This is intended to replace the original Secondary Index feature and has the potential to radically change your application data model.
2. *Trie Memtables and Trie SSTables*
These low-level optimizations yield impressive gains in memory usage and storage efficiency, providing a "free" performance boost without requiring changes to your data model. An online upgrade of your cluster will give you immediate access to this new feature with just a few configuration changes. 
3. *Java Development Kit (JDK) 17 Support*
The long-awaited upgrade to JDK 17 brings performance improvements of up to 20% in some cases, thanks to enhanced memory management capabilities. In addition, this allows Cassandra operators to take advantage ot the exciting changes to garbage collection that were made available. 
4. *Unified Compaction Strategy (UCS)*
UCS acts as an autopilot for data organization, automatically adjusting to changing requirements as your cluster grows. This feature significantly enhances operational efficiency, especially for large-scale deployments, greatly increasing node density. 
5. *Vector Search*
With the introduction of a vector data type and indexing for Approximate Nearest Neighbor searches, Cassandra 5.0 lays the groundwork for advanced AI and machine learning applications. Developers building Generative AI applications can combine Cassandra's scale and distribution with the latest search technology. 
6. Dynamic Data Masking
New dynamic data masking capabilities allow for the obfuscation of sensitive information using masked columns, enhancing data security without altering the stored data. This can be done at runtime using the SELECT syntax or integrated at the server level using schema definitions and role-based security.

## Important: End-of-Life Announcement for Cassandra 3.x Series
As we celebrate this new release, we must also remind everyone of an important transition: With the release of Apache Cassandra® 5.0, we officially announce the end-of-life (EOL) for the 3.x series, including versions 3.0 and 3.11. We strongly urge all users to plan their upgrade strategy as soon as possible to ensure continued support and access to the latest bug and security fixes.

Key points regarding the EOL announcement:

 - The Cassandra community will evaluate security patches contributed to unmaintained branches on a case-by-case basis.
 - CVE fixes may be applied to unmaintained versions, but this is not guaranteed.
 - Users are encouraged to transition to version 4.0 or later to benefit from ongoing support and maintenance.

### Upgrading to Apache Cassandra® 5.0

Upgrading from 4.x to 5.0 has been designed and tested as an online upgrade, minimizing downtime for your applications. 

Apache Cassandra® 5.0 is available as a download package, deb or RPM file. Refer to the https://cassandra.apache.org/_/download.html[downloads] page for details.

## Community Involvement
The Apache Cassandra® community has been instrumental in shaping this release. We invite you to get involved:

 - Participate in discussions on our mailing list and Slack channel
 - Contribute code, documentation, or use cases
 - Share your experiences and insights with the community
 - Meet us in Denver October 7-10, 2024, to learn more about Apache Cassandra® 5.0. Details at http://www.communityovercode.org[www.communityovercode.org]

Apache Cassandra® 5.0 represents the collaborative efforts of a vibrant open-source community. We're excited to see how you'll leverage these new capabilities to build the next generation of scalable, resilient applications.
