= Cassandra Summit Returns in 2023
:page-layout: single-post
:page-role: blog-post
:page-post-date: September 29, 2022
:page-post-author: The Apache Cassandra Community
:description: Cassandra Summit announcement
:keywords: 

https://events.linuxfoundation.org/cassandra-summit/[Cassandra Summit] is returning in 2023! We have been apart far too long and it's time for the Apache Cassandra community to gather again. 

Cassandra Summit 2023 will be held in San Jose, Calif., March 13-14, 2023, with pre-event training and activities planned for March 12. We are partnering with the world-class events team at the Linux Foundation to create a two-day, vendor-neutral event where we'll all come together to share best practices and use cases, celebrate makers and users, forge critical relationships, and learn about advancements in the Apache Cassandra ecosystem. 

You'll get to take in exciting keynotes and participate in hands-on labs, sessions, and the popular hallway track, with a focus on the following topics:

* Developing applications with Cassandra
* Cloud-native deployments and strategies
* Ecosystem tools that leverage Cassandra
* What’s coming for future Cassandra versions
* Use cases and sharing about best practices

Get ready for a lot of fun too. There will be many places to make community memories in a festival-like atmosphere with experiential, interactive exhibits and entertainment breaks.

All the details can be found at the https://events.linuxfoundation.org/cassandra-summit/[Cassandra Summit website]. If you're interested in sponsorships, we welcome you to reach out to sponsorships@linuxfoundation.org. Be sure to keep an eye out for the https://events.linuxfoundation.org/cassandra-summit/program/cfp/[call for proposals], opening in October 2022. If you have a case study, best practice or idea for a talk that could help others in the Cassandra community, we want to hear from you.

Come join us to celebrate what we've built together and learn about what's next. We hope to see you there!