= Cassandra Contributor November Meeting Replay
:page-layout: single-post
:page-role: blog-post
:page-post-date: January 2, 2024
:page-post-author: The Apache Cassandra Community
:description: The Apache Cassandra Community
:keywords: 

Cassandra Contributor November Meeting Replay

The Apache Cassandra community hosts informal monthly meetings to enable real-time collaboration for contributors to discuss CEPs and other issues, and ask questions. 


November’s meeting discussed the upcoming Apache Cassandra 5.0 release xref:Apache-Cassandra-5.0-Moving-Toward-an-AI-Driven-Future.adoc[Apache Cassandra 5.0 Release Preview]
 
_Meetings take place the last Tuesday of each month at 10:00 PT / 13:00 ET / 17:00 UTC._

== Watch the Recording 

video::JSDivLidnOg[youtube,JSDivLidnOg,width=560,height=315]

To view previous meeting agenda and notes, visit the https://cwiki.apache.org/confluence/x/qo7JC[Apache Cassandra Wiki page^].  

*Ways to Participate*


For more information or to join the discussion, join us on these channels: 

* https://calendar.google.com/calendar/b/1?cid=a2w5cHVoZ2s3cXRkdXFhdHRlOHRmZDVtcHNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ[Cassandra Community Meeting Calendar^]
* xref:index.adoc[Apache Cassandra Website]
* https://the-asf.slack.com/ssb/redirect[ASF Slack^]
* https://planetcassandra.org/[Planet Cassandra Website^]
* https://discord.com/invite/Ut8YctQWac[Planet Cassandra Discord^]
