= Town Hall Replay: Bad Partition Handling \& Large Language Models
:page-layout: single-post
:page-role: blog-post
:page-post-date: August 16, 2023
:page-post-author: The Apache Cassandra Community
:description: A recap of the June Town Hall
:keywords: meetup, event

Apache Cassandra Town Halls are monthly opportunities to share use cases, tips, and learn about Cassandra project news. If you are an Apache Cassandra end user or part of the Cassandra engineering community, Town Halls are a great way to stay up-to-date on community activities.

_Town halls occur at 8am PT on the fourth Thursday of every month._

**Improving Bad Partition Handling in Apache Cassandra**

Presented by https://www.linkedin.com/in/jordan-west-8aa1731a3/[Jordan West^] and https://www.linkedin.com/in/cheng-wang-10323417/[Cheng Wang^], Netflix

Reading and compacting bad partitions have long been known to impact Cassandra performance. They have been the root cause of various production issues at Netflix. While there are several potential solutions for addressing them at an implementation level, we must also deal with them today when they arise. There are several forms of bad partitions, which include: a partition that gets large in size several GBs+; a partition with many (millions or more) small rows, potentially spread across many sstables; a partition with many small rows and many of them have been deleted or expired; and a partition with rows that themselves are very large (e.g. blobs of binary or text). This talk presents an approach used at Netflix to handle bad partitions when they arise. Specifically, how to identify, block, and mitigate bad partitions during production incidents. Jordan and Cheng also share ongoing efforts to improve some existing tools as well as new tools for the Cassandra community. 

**Unleashing the Power of Large Language Models with Apache Cassandra and Vector Search**

Presented by https://www.linkedin.com/in/jbellis/[Jonathan Ellis^], DataStax

In this talk, Jonathan explores the transformative role of Large Language Models (LLMs) like GPT-4 in developing AI-powered applications. Jonathan also covers how LLMs simplify traditional AI processes, reducing the need for complex data pipelines and bespoke model training to straightforward text-based inputs and queries. Through real-world application examples, Jonathan highlights the potential of LLMs in creating efficient AI systems, and the role of vector search. 

**Apache Cassandra Project Updates**

Presented by http://in/josh-mckenzie-59b38b14[Josh McKenzie^], Cassandra PMC Chair

video::OkqyUdxQPBg[youtube,OkqyUdxQPBg,width=560,height=315]

### Ways to Participate

To catch an upcoming Town Hall, check out our https://www.meetup.com/cassandra-global/[Planet Cassandra Global Meetup Group^]. To view previous Town Hall recordings, visit the https://www.youtube.com/watch?v=f0F0dCThQ40&list=PLqcm6qE9lgKKpeO7AgGWcLB6dsz0vS4y1[Planet Cassandra YouTube Channel^]. 

If you’re interested in sharing a case study or use case with the community, https://docs.google.com/forms/d/e/1FAIpQLScsRrS02giJRklynroTeBV7mkEH3Oc_n_hU0ZZM82VKiBnNnw/viewform[let us know^]. 

For more information or to join the discussion, join us on these channels: 

* https://cassandra.apache.org/_/index.html[Apache Cassandra Website]
* https://the-asf.slack.com/ssb/redirect[ASF Slack^]
* https://planetcassandra.org/[Planet Cassandra Website^]
* https://discord.com/invite/Ut8YctQWac[Planet Cassandra Discord^]