= Town Hall Replay: Time Series Data Modeling for Massive Scale
:page-layout: single-post
:page-role: blog-post
:page-post-date: August 23, 2023
:page-post-author: The Apache Cassandra Community
:description: A recap of the July Town Hall
:keywords: meetup, event

Apache Cassandra Town Halls are monthly opportunities to share use cases, tips, and learn about Cassandra project news. If you are an Apache Cassandra end user or part of the Cassandra engineering community, Town Halls are a great way to stay up-to-date on community activities.

_Town halls occur at 8am PT on the fourth Thursday of every month._

**Time Series Data Modeling for Massive Scale**

Presented by https://www.linkedin.com/in/rustyrazorblade/[Jon Haddad^], Rustyrazorblade Consulting

Cassandra is known for its ability to horizontally scale as your data increases, but to get the most value, you need to know a few tricks. Jon has been optimizing databases for two decades, with the last ten years focused on Cassandra. In this Town Hall, Jon demonstrates how to handle one of the biggest Cassandra challenges of all: efficiently storing and retrieving over a petabyte of time series data accumulated over several years. He also covers some of the common pitfalls you’ll run into and the approach you should take to avoid each of them.

**Apache Cassandra Project Updates**

Presented by http://in/josh-mckenzie-59b38b14[Josh McKenzie^], Cassandra PMC Chair

video::keG_f8tDoVI[youtube,keG_f8tDoVI,width=560,height=315]

### Ways to Participate

To catch an upcoming Town Hall, check out our https://www.meetup.com/cassandra-global/[Planet Cassandra Global Meetup Group^]. To view previous Town Hall recordings, visit the https://www.youtube.com/watch?v=f0F0dCThQ40&list=PLqcm6qE9lgKKpeO7AgGWcLB6dsz0vS4y1[Planet Cassandra YouTube Channel^]. 

If you’re interested in sharing a case study or use case with the community, https://docs.google.com/forms/d/e/1FAIpQLScsRrS02giJRklynroTeBV7mkEH3Oc_n_hU0ZZM82VKiBnNnw/viewform[let us know^]. 

For more information or to join the discussion, join us on these channels: 

* https://cassandra.apache.org/_/index.html[Apache Cassandra Website]
* https://the-asf.slack.com/ssb/redirect[ASF Slack^]
* https://planetcassandra.org/[Planet Cassandra Website^]
* https://discord.com/invite/Ut8YctQWac[Planet Cassandra Discord^]
