= Town Hall Replay: Cassandra Performance Tuning Like You\'ve Been Doing it For Ten Years
:page-layout: single-post
:page-role: blog-post
:page-post-date: July 27, 2023
:page-post-author: The Apache Cassandra Community
:description: Recap of the inaugural Apache Cassandra Town Hall.
:keywords: 

In April the Apache Cassandra community launched a monthly Town Hall series to provide a place for end users to talk about their use of Cassandra; for the Cassandra engineering community to share projects and release updates; and for Cassandra users and enthusiasts to come together and stay up-to-date on community activities. You can find a brief overview of what was discussed and watch the full replay below. 

**Cassandra Performance Tuning Like You've Been Doing It For Ten Years**

Presented by Jon Haddad, Cassandra Committer

Database tuning can be intimidating if you don’t know where to start, and it’s even harder when it’s a distributed database like Cassandra. Using Cassandra’s out of the box configuration works well for laptops but falls far short of its total potential in production. During the Town Hall, Jon explored how to diagnose common performance problems and highlighted some tools and processes for getting to the bottom of any issue, quickly. To help Cassandra users up their game, Jon also shared some of the most impactful and novel tips. He promises lower latency, higher throughput, and fewer headaches! 

**Apache Cassandra 5.0 Release Update**

Presented by Josh McKenzie, Cassandra PMC Chair

video::f0F0dCThQ40[youtube,f0F0dCThQ40,width=560,height=315]

### Ways to Participate

To catch an upcoming Town Hall, check out our https://www.meetup.com/cassandra-global/[Planet Cassandra Global Meetup Group^].

For more information or to join the discussion, join us on these channels:

* https://cassandra.apache.org/_/index.html[Apache Cassandra Website]
* https://bit.ly/3Aez8nx[ASF Slack #cassandra^]
* https://planetcassandra.org/[Planet Cassandra Website^]
* https://discord.gg/Ut8YctQWac[Planet Cassandra Discord^]
