= Town Hall Replay: mondayDB Architecture - Crafting a Database From Scratch
:page-layout: single-post
:page-role: blog-post
:page-post-date: January 2, 2024
:page-post-author: The Apache Cassandra Community
:description: A recap of the November Town Hall - monday.com
:keywords: meetup, event

Apache Cassandra Town Halls are monthly opportunities to share use cases, tips, and learn about Cassandra project news. If you are an Apache Cassandra end user or part of the Cassandra engineering community, Town Halls are a great way to stay up-to-date on community activities. 

_Town halls occur at 8am PT on the fourth Thursday of every month._

***mondayDB Architecture - Crafting a Database From Scratch***

_Presented by https://www.linkedin.com/in/liran-brimer[Liran Brimer^], Senior Tech Lead, monday.com_

In this Town Hall, Liran presents the complex challenges monday.com faced when implementing its in-house data engine, mondayDB. Liran demonstrates how they shifted their entire data paradigm, the creative solutions the organization crafted in response, and the remarkable benefits monday.com has seen as a result. Watch the link to delve into the technical details of the architecture, including the use of columnar storage, lambda architecture, Apache Cassandra as the storage layer, and more.

video::1DzQI22cJ9U[youtube,1DzQI22cJ9U,width=560,height=315]

https://www.youtube.com/watch?v=1DzQI22cJ9U&list=PLqcm6qE9lgKKpeO7AgGWcLB6dsz0vS4y1&index=9 

### Ways to Participate

To catch an upcoming Town Hall, check out our https://www.meetup.com/cassandra-global/[Planet Cassandra Global Meetup Group^]. To view previous Town Hall recordings, visit the https://www.youtube.com/playlist?list=PLqcm6qE9lgKKpeO7AgGWcLB6dsz0vS4y1[Planet Cassandra YouTube Channel^]. 

If you’re interested in sharing a case study or use case with the community, https://docs.google.com/forms/d/e/1FAIpQLScsRrS02giJRklynroTeBV7mkEH3Oc_n_hU0ZZM82VKiBnNnw/viewform[let us know^]. 

For more information or to join the discussion, join us on these channels: 

* https://cassandra.apache.org/_/index.html[Apache Cassandra Website]
* https://the-asf.slack.com/ssb/redirect[ASF Slack^]
* https://planetcassandra.org/[Planet Cassandra Website^]
* https://discord.com/invite/Ut8YctQWac[Planet Cassandra Discord^]
