= Town Hall Replay: Cassandra 5.0 Features We’re Excited About
:page-layout: single-post
:page-role: blog-post
:page-post-date: September 30, 2023
:page-post-author: The Apache Cassandra Community
:description: A recap of the September Town Hall
:keywords: meetup, event

Apache Cassandra Town Halls are monthly opportunities to share use cases, tips, and learn about Cassandra project news. If you are an Apache Cassandra end user or part of the Cassandra engineering community, Town Halls are a great way to stay up-to-date on community activities. 

_Town halls occur at 8am PT on the fourth Thursday of every month._

**Features everyone is looking forward to in Apache Cassandra 5.0**

Presented by https://www.linkedin.com/in/aaronploetz/[Aaron Ploetz^] Developer Advocate @ DataStax

Apache Cassandra 5.0 is the project’s major release for 2023! With a focus on machine learning and artificial intelligence, this release brings a host of exciting features and enhancements that empower you to take your data-driven applications to the next level. In this Town Hall, Aaron Ploetz dives into some of the features the community is most excited about. 

video::XvWQ907OC1w[youtube,XvWQ907OC1w,width=560,height=315]

### Ways to Participate

To catch an upcoming Town Hall, check out our https://www.meetup.com/cassandra-global/[Planet Cassandra Global Meetup Group^]. To view previous Town Hall recordings, visit the https://www.youtube.com/watch?v=f0F0dCThQ40&list=PLqcm6qE9lgKKpeO7AgGWcLB6dsz0vS4y1[Planet Cassandra YouTube Channel^]. 

If you’re interested in sharing a case study or use case with the community, https://docs.google.com/forms/d/e/1FAIpQLScsRrS02giJRklynroTeBV7mkEH3Oc_n_hU0ZZM82VKiBnNnw/viewform[let us know^]. 

For more information or to join the discussion, join us on these channels: 

* https://cassandra.apache.org/_/index.html[Apache Cassandra Website]
* https://the-asf.slack.com/ssb/redirect[ASF Slack^]
* https://planetcassandra.org/[Planet Cassandra Website^]
* https://discord.com/invite/Ut8YctQWac[Planet Cassandra Discord^]
