= Town Hall Replay: Monitoring Apache Cassandra Without Implementation
:page-layout: single-post
:page-role: blog-post
:page-post-date: August 2, 2023
:page-post-author: The Apache Cassandra Community
:description: A recap of the May Town Hall
:keywords: meetup, event

After a great inaugural meetup, we hosted the second Apache Cassandra town hall in May. If you are an Apache Cassandra end user or part of the Cassandra engineering community, town halls are a great way to share project and release updates and stay up-to-date on community activities. 

_Town halls occur at 8am PT on the fourth Thursday of every month._

**Monitoring Cassandra Without Instrumentation Using eBPF**

Presented by https://www.linkedin.com/in/domenic-del-nano-5135899b[Dom Del Nano^], Pixie

Imagine a world where you can access metrics and full-body traces in seconds, without changing your code. In this town hall, Dom gave an overview of eBPF, a powerful Linux kernel technology that is fundamentally changing the fields of observability, networking and security. He presented a live demo showing eBPF monitoring of Cassandra using only open source projects. Dom also showed us how to use Pixie, a eBPF-based Kubernetes observability tool, to quickly identify services and pods that send and receive Cassandra requests, inspect individual requests and responses, and calculate request latency, error rate, and throughput. This was a great presentation for those interested in Cassandra observability! 

**Apache Cassandra 5.0 Release Update**

Presented by Josh McKenzie, Cassandra PMC Chair

**CEP-28: Reading and Writing Cassandra Data with Spark Bulk Analytics**

Presented by Dinesh Joshi, Cassandra PMC member and software engineer at Apple

### Watch the Replay

video::23-QqIBORNg[youtube,23-QqIBORNg,width=560,height=315]

If you’d like to learn more about CEP-28, you can watch the full replay of the Apache Cassandra Contributor Meeting where Dinesh walks us through the project in more detail. 

video::gImCuUCwb0Q[youtube,gImCuUCwb0Q,width=560,height=315]

### Ways to Participate

To catch an upcoming Town Hall, check out our Planet Cassandra Global Meetup Group.  

If you’re interested in sharing a case study or use case with the community, let us know. 

For more information or to join the discussion, join us on these channels:

* https://cassandra.apache.org/_/index.html[Apache Cassandra Website]
* https://the-asf.slack.com/ssb/redirect[ASF Slack^]
* https://planetcassandra.org/[Planet Cassandra Website^]
* https://discord.com/invite/Ut8YctQWac[Planet Cassandra Discord^]