= Town Hall Replay: Cassandra Performance Tuning Like You’ve Been Doing it For Ten Years
:page-layout: single-post
:page-role: blog-post
:page-post-date: June 17, 2023
:page-post-author: The Apache Cassandra Community
:description: Recap of the inaugural Apache Cassandra Town Hall.
:keywords: 

Town Hall Replay: Monitoring Apache Cassandra Without Implementation

After a great inaugural meetup, we hosted the second Apache Cassandra town hall in May. If you are an Apache Cassandra end user or part of the Cassandra engineering community, town halls are a great way to share project and release updates and stay up-to-date on community activities. 

Town halls occur at 8am PT on the fourth Thursday of every month.

Monitoring Cassandra Without Instrumentation Using eBPF
Presented by Dom Del Nano, Pixie
Imagine a world where you can access metrics and full-body traces in seconds, without changing your code. In this town hall, Dom gave an overview of eBPF, a powerful Linux kernel technology that is fundamentally changing the fields of observability, networking and security. He presented a live demo showing eBPF monitoring of Cassandra using only open source projects. Dom also showed us how to use Pixie, a eBPF-based Kubernetes observability tool, to quickly identify services and pods that send and receive Cassandra requests, inspect individual requests and responses, and calculate request latency, error rate, and throughput. This was a great presentation for those interested in Cassandra observability! 

Apache Cassandra 5.0 Release Update
Presented by Josh McKenzie, Cassandra PMC Chair

CEP-28: Reading and Writing Cassandra Data with Spark Bulk Analytics
Presented by Dinesh Joshi, Cassandra PMC member and software engineer at Apple

https://www.youtube.com/watch?v=23-QqIBORNg&list=PLqcm6qE9lgKKpeO7AgGWcLB6dsz0vS4y1&index=3
<iframe width="560" height="315" src="https://www.youtube.com/embed/23-QqIBORNg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

If you’d like to learn more about CEP-28, you can watch the full replay of the Apache Cassandra Contributor Meeting where Dinesh walks us through the project in more detail. 

https://www.youtube.com/watch?v=gImCuUCwb0Q&list=PLqcm6qE9lgKKls90MlpejceYUU_0qVnWa&index=9
<iframe width="560" height="315" src="https://www.youtube.com/embed/gImCuUCwb0Q" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
Ways to Participate

To catch an upcoming Town Hall, check out our Planet Cassandra Global Meetup Group.  

If you’re interested in sharing a case study or use case with the community, let us know. 

For more information or to join the discussion, join us on these channels: 
Apache Cassandra Website 
ASF Slack
Planet Cassandra Website 
Planet Cassandra Discord 

# # # 



As the Apache Cassandra® community grows, it is important that we have dedicated forums to gather, share, and learn. With this in mind, we are kicking off monthly live, virtual Town Hall meetings starting this month. **Our very first Town Hall is on April 26 at 9am PT, and https://www.meetup.com/cassandra-global/events/292858262/[you can register here^]**. We’ll also be hosting an “Ask Me Anything” (AMA) on https://discord.com/invite/Ut8YctQWac[Planet Cassandra Discord^] following the event.

### What to expect from Cassandra Town Halls

Our goal with Town Halls is to provide a forum for users of Cassandra to come together - whether you’re brand new or have been using it for years. During the meetings you can share what you’ve learned on your Cassandra journey and hear valuable lessons from your peers. You can expect project and release updates from community leaders, as well as  info about what’s coming for Cassandra, and guidance on how you can participate. 

Going forward, meetings are scheduled to be live-streamed on Zoom the **fourth Thursday of the month at 8am PT**. However, we want to find a time that works for most, so https://calendly.com/d/z2m-jps-68c/may-cassandra-town-hall-virtual-meeting[please take this poll^] to let us know what works best for you. We’ll do our best to adjust accordingly. We’ll also make recordings immediately available on https://www.youtube.com/@PlanetCassandra/streams[the Planet Cassandra YouTube channel^]. 

### Agenda for our first Town Hall

For our inaugural event, we are  excited that https://www.linkedin.com/in/rustyrazorblade/[Jon Haddad^] will share what Netflix has learned along their Cassandra journey. Project Management Committee lead, https://www.linkedin.com/in/josh-mckenzie-59b38b14/[Josh MacKenzie^] will also give a project update. There will be space to meet each other and ask questions.

### Join the post-Town Hall Discord AMA

Immediately after our Town Hall (April 26 at 10am PT), join our hosts and the community on the Planet Cassandra Discord for an AMA. This AMA is an extension of the Town Hall, offering more time and space for you to learn and engage. We’ll be there live until 11am PT,  but rest assured, if you’re not there live, we’ll be checking back frequently to answer questions async throughout the day.

### How to Join the Meeting

Ready to attend? Copy the invite from the public https://calendar.google.com/calendar/u/0?cid=a2w5cHVoZ2s3cXRkdXFhdHRlOHRmZDVtcHNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ[Cassandra Community Meeting Calendar^]. 

Hope to see you there! And as always, don’t be shy about sharing feedback on Town Halls. We want these to be useful for you, and your input is valuable.

* https://discord.gg/Ut8YctQWac[Planet Cassandra Discord^]
* https://www.youtube.com/@PlanetCassandra/streams[Planet Cassandra YouTube^] (for replays)
* https://bit.ly/3Aez8nx[ASF Slack #cassandra^]
* https://planetcassandra.org/[Planet Cassandra Website^]
