= Town Hall Replay: Cassandra at Walmart
:page-layout: single-post
:page-role: blog-post
:page-post-date: December 8, 2023
:page-post-author: The Apache Cassandra Community
:description: A recap of the October Town Hall
:keywords: meetup, event

Apache Cassandra Town Halls are monthly opportunities to share use cases, tips, and learn about Cassandra project news. If you are an Apache Cassandra end user or part of the Cassandra engineering community, Town Halls are a great way to stay up-to-date on community activities. 

_Town halls occur at 8am PT on the fourth Thursday of every month._

**Cassandra at Walmart**

Presented by https://www.linkedin.com/in/patrick-lee-7ba2b8b[Patrick Lee^], Principal Software Engineer @ Walmart

A discussion on Walmart's successful use of Apache Cassandra to enhance data management, exploring the development of a streamlined managed offering and sharing insights from the recent upgrade to Cassandra 4. Watch to delve into Walmart's innovative use of Cassandra and its impact on data-driven operations.

video::zIHkSLYVvMM[youtube,zIHkSLYVvMM,width=560,height=315]

### Ways to Participate

To catch an upcoming Town Hall, check out our https://www.meetup.com/cassandra-global/[Planet Cassandra Global Meetup Group^]. To view previous Town Hall recordings, visit the https://www.youtube.com/watch?v=f0F0dCThQ40&list=PLqcm6qE9lgKKpeO7AgGWcLB6dsz0vS4y1[Planet Cassandra YouTube Channel^]. 

If you’re interested in sharing a case study or use case with the community, https://docs.google.com/forms/d/e/1FAIpQLScsRrS02giJRklynroTeBV7mkEH3Oc_n_hU0ZZM82VKiBnNnw/viewform[let us know^]. 

For more information or to join the discussion, join us on these channels: 

* https://cassandra.apache.org/_/index.html[Apache Cassandra Website]
* https://the-asf.slack.com/ssb/redirect[ASF Slack^]
* https://planetcassandra.org/[Planet Cassandra Website^]
* https://discord.com/invite/Ut8YctQWac[Planet Cassandra Discord^]
