= Town Hall Replay: Josh McKenzie
:page-layout: single-post
:page-role: blog-post
:page-post-date: January 2, 2023
:page-post-author: The Apache Cassandra Community
:description: A recap of the November Town Hall - Josh McKenzie
:keywords: meetup, event

Apache Cassandra Town Halls are monthly opportunities to share use cases, tips, and learn about Cassandra project news. If you are an Apache Cassandra end user or part of the Cassandra engineering community, Town Halls are a great way to stay up-to-date on community activities. 

_Town halls occur at 8am PT on the fourth Thursday of every month._

***The State of the Cassandra Development Community***

_Presented by https://www.linkedin.com/in/josh-mckenzie-59b38b14[Josh McKenzie^], Software Engineer, Apple & PMC Chair, Apache Cassandra_

In this Town Hall, Josh discusses the state of the Apache Cassandra development community over the past half-decade: where the community has been, where it is, and where it's headed. He discusses the impact of personalities entering and leaving the community; how perspectives grow and change; the current state of the contributor ecosystem; and the importance of building a consensus, which remains challenging but a vital task to the long-term health of the project.

video::fdH5_6PPy9M[youtube,fdH5_6PPy9M,width=560,height=315]

### Ways to Participate

To catch an upcoming Town Hall, check out our https://www.meetup.com/cassandra-global/[Planet Cassandra Global Meetup Group^]. To view previous Town Hall recordings, visit the https://www.youtube.com/playlist?list=PLqcm6qE9lgKKpeO7AgGWcLB6dsz0vS4y1[Planet Cassandra YouTube Channel^]. 

If you’re interested in sharing a case study or use case with the community, https://docs.google.com/forms/d/e/1FAIpQLScsRrS02giJRklynroTeBV7mkEH3Oc_n_hU0ZZM82VKiBnNnw/viewform[let us know^]. 

For more information or to join the discussion, join us on these channels: 

* xref:index.adoc[Apache Cassandra Website]
* https://the-asf.slack.com/ssb/redirect[ASF Slack^]
* https://planetcassandra.org/[Planet Cassandra Website^]
* https://discord.com/invite/Ut8YctQWac[Planet Cassandra Discord^]
