:page-layout: basic

== Dependency Management

Managing libraries for Cassandra is a bit less straight forward compared
to other projects, as the build process is based on ant, maven and
manually managed jars. Make sure to follow the steps below carefully and
pay attention to any emerging issues in the `ci` and reported related
issues on Jira/ML, in case of any project dependency changes.

As Cassandra is an Apache product, all included libraries must follow
Apache's https://www.apache.org/legal/resolved.html[software license
requirements].

=== Changes to dependency management in Cassandra 4.2

Before Cassandra 4.2, dependencies were managed in `build.xml` and managed with
Maven Ant Tasks. In Cassandra 4.2 and onwards, dependencies are managed in POM
templates in `.build/`. New dependencies should be added to the parent POM
template and necessary child POMs. See
https://issues.apache.org/jira/browse/CASSANDRA-17750[CASSANDRA-17750] for more
information.

=== Required steps to add or update libraries

* Add or replace jar file in `lib` directory
* Add or update `lib/license` files
* Update dependencies in `build.xml` (pre-4.2) or POM templates in `.build/` (4.2 onwards)
* If dependencies are managed in `build.xml` (pre-4.2):
** Add to `parent-pom` with correct version
** Add to `all-pom` if simple Cassandra dependency (see below)
* If dependencies are managed in POM templates in `.build/`  (4.2 onwards):
** Add dependency to `.build/parent-pom-template.xml` with correct version and optional scope and classifier
** Add dependency to `.build/cassandra-deps-template.xml` and optionally `.build/cassandra-build-deps-template.xml` with references to parent POM

=== POM file types

* *parent-pom* - contains all dependencies with the respective version.
All other poms will refer to the artifacts with specified versions
listed here.
* *build-deps-pom(-sources)* + *coverage-deps-pom* - used by `ant build`
compile target. Listed dependenices will be resolved and copied to
`build/lib/{jar,sources}` by executing the
`maven-ant-tasks-retrieve-build` target. This should contain libraries
that are required for build tools (grammar, docs, instrumentation), but
are not shipped as part of the Cassandra distribution.
* *test-deps-pom* - refered by `maven-ant-tasks-retrieve-test` to
retrieve and save dependencies to `build/test/lib`. Exclusively used
during JUnit test execution.
* *all-pom* - pom for
https://mvnrepository.com/artifact/org.apache.cassandra/cassandra-all[cassandra-all.jar]
that can be installed or deployed to public maven repos via
`ant publish`

=== Troubleshooting and conflict resolution

Here are some useful commands that may help you out resolving conflicts.

* `ant realclean` - gets rid of the build directory, including build
artifacts.
* `mvn dependency:tree -f build/apache-cassandra-*-SNAPSHOT.pom -Dverbose -Dincludes=org.slf4j`
- shows transitive dependency tree for artifacts, e.g. org.slf4j. In
case the command above fails due to a missing parent pom file, try
running `ant mvn-install`.
* `rm ~/.m2/repository/org/apache/cassandra/apache-cassandra/` - removes
cached local Cassandra maven artifacts
