:page-layout: basic

== Getting Started

=== Initial Contributions

Writing a new feature is just one way to contribute to the Cassandra
project.
In fact, making sure that supporting tasks, such as quality testing,
documentation, and helping users are completed is just as important.
Tracking the development of new features is an ongoing challenge for this project,
like most open source projects.
We suggest learning how this project gets things done before tackling a new feature.
Here are some suggestions for ways to contribute:

* Update the documentation
* Answer questions on the user list
* Review and test a submitted patch
* Investigate and fix a reported bug
* Create unit tests and d-tests

=== Updating documentation

The Cassandra documentation is maintained in the Cassandra source
repository along with the Cassandra code base.
To submit changes to the documentation, follow the standard process for
submitting a xref:development/patches.adoc[patch].

=== Answering questions on the user list

Subscribe to the user list, look for some questions you can answer and write a reply.
Simple as that! See the http://cassandra.apache.org/community/[community] page
for details on how to subscribe to the mailing list.

=== Reviewing and testing a submitted patch

Reviewing patches is not the sole domain of committers.
If others review a patch, it can reduce the load on the committers.
Less time spent reviewing patches means committers can more great features
or review more complex patches.
Follow the instructions in xref:development/how_to_review.adoc[How to review] or alternatively, create a build with the patch and test it with your own workload.
Add a comment to the JIRA ticket to let others know you've reviewed and tested,
along with the results of your work.
For example:

====
"I tested this performance enhancement on our application's standard production
load test and found a 3% improvement."
====

=== Investigate and/or fix a reported bug

Often, the hardest work in fixing a bug is reproducing it.
Even if youdon't have the knowledge to produce a fix, figuring out a way to
reliably reproduce an issue can be a massive contribution.
Document your method of reproduction in a JIRA comment or,
better yet, produce an automated test that reproduces the issue and
attach it to the ticket.
If you go as far as producing a fix, follow the process for submitting a xref::patches.adoc[patch].

To create a JIRA account, please request it on xref:community.adoc#discussions[the #cassandra or #cassandra-dev channels on ASF Slack], or on xref:community.adoc#discussions[the user or dev mailing list].

=== Create unit tests and Dtests

Test coverage for Cassandra will always benefit from more automated test
coverage, as with most code bases.
Before starting work on a particular area of code, consider reviewing and
enhancing the existing test coverage.
You'll both improve your knowledge of the code before you start on an
enhancement, and reduce the chance introducing issues with your change. See xref:development/testing.adoc[testing] and xref:development/patches.adoc[patches] for more detail.
