= Reporting Bugs
:page-layout: basic
:page-role: bugs
:description:

If you encounter a problem with Cassandra, the first places to ask for help are the 
link:++https://lists.apache.org/list.html?user@cassandra.apache.org++[user mailing list] and 
the https://s.apache.org/slack-invite[Cassandra slack room].

If, after having asked for help, you suspect that you have found a bug
in Cassandra, you should report it by opening a ticket through the
https://issues.apache.org/jira/browse/CASSANDRA[Apache Cassandra JIRA].
Please provide as much details as you can on your problem, and don't
forget to indicate which version of Cassandra you are running and on
which environment.

To create a JIRA account, please request it on xref:community.adoc#discussions[the #cassandra or #cassandra-dev channels on ASF Slack], or on xref:community.adoc#discussions[the user or dev mailing list].

Further details on how to contribute can be found at our
xref:community.adoc#how-to-contribute[Contributing to Cassandra] section. Please note that the source of this
documentation is part of the Cassandra git repository and hence
contributions to the documentation should follow the same path.
