= Community

== Getting and keeping in touch

== Mailing lists

Discussion and questions on Cassandra’s usage and development happens
mainly on the following mailing lists:

* http://www.mail-archive.com/user@cassandra.apache.org/[Users]: General
mailing list for user questions and discussions. This is also where new
releases are announced
(mailto:user-subscribe@cassandra.apache.org[subscribe] |
mailto:user-unsubscribe@cassandra.apache.org[unsubscribe] |
https://lists.apache.org/list.html&#63;user&#64;cassandra.apache.org[Archives]).
* http://www.mail-archive.com/dev@cassandra.apache.org/[Developers]:
Questions and discussions related to Cassandra development
(mailto:dev-subscribe@cassandra.apache.org[subscribe] |
mailto:dev-unsubscribe@cassandra.apache.org[unsubscribe] |
https://lists.apache.org/list.html&#63;dev&#64;cassandra.apache.org[Archives]).
* http://www.mail-archive.com/commits@cassandra.apache.org/[Commits]:
Notification on commits done to the source repository and on
https://issues.apache.org/jira/browse/CASSANDRA[JIRA] updates. This is a
fairly noisy mailing list mostly useful for Cassandra developers and
those who would like to keep close tabs on Cassandra’s development
(mailto:commits-subscribe@cassandra.apache.org[subscribe] |
mailto:commits-unsubscribe@cassandra.apache.org[unsubscribe] |
https://lists.apache.org/list.html&#63;commits&#64;cassandra.apache.org[Archives]).

== Slack

We have recently moved to the ASF Slack organization for all chat.
Please https://s.apache.org/slack-invite[sign up for an account] to
participate.

* `#cassandra` - for user questions and general discussions
* `#cassandra-dev` - strictly for questions or discussions related to
Cassandra development
* `#cassandra-builds` - results of automated test builds
* `#cassandra-builds-patches` - results of patch test builds

== Stack Overflow

You can also check the
http://stackoverflow.com/questions/tagged/cassandra[Q&A about using
Cassandra] on Stack Overflow.

== Books and publications

* http://shop.oreilly.com/product/0636920299837.do[Cassandra: The
Definitive Guide, 3rd Edition], by Jeff Carpenter and Eben Hewitt.
Updated for Cassandra 4.0
* https://www.amazon.com/Mastering-Apache-Cassandra-Nishant-Neeraj/dp/1784392618/[Mastering
Apache Cassandra, 2nd Edition], by Nishant Neeraj
* https://www.amazon.com/Learning-Apache-Cassandra-Tolerant-Real-Time/dp/1783989203/[Learning
Apache Cassandra - Manage Fault Tolerant and Scalable Real-Time Data],
by Mat Brown
* https://dl.acm.org/citation.cfm?id=1773922[Cassandra: a decentralized
structured storage system], by Avinash Lakshman and Prashant Malik

== Third-party projects

There are a number of third-party Cassandra projects that could be
useful. Check out this
https://cassandra.apache.org/third-party/[listing].

== Reporting bugs

If you encounter a problem with Cassandra, the first places to ask for
help are the link:#mailing[user mailing list] and the `#cassandra`
https://s.apache.org/slack-invite[Slack channel].

If, after having asked for help, you suspect that you have found a bug
in Cassandra, you should report it by opening a ticket through the
https://issues.apache.org/jira/browse/CASSANDRA[Apache Cassandra JIRA
tracking system]. Please provide as much detail as you can on your
problem. Don’t forget to indicate which version of Cassandra you are
running and on which environment.
