= Contact us

You can get in touch with the Cassandra community either via the mailing
lists or Slack rooms.

== Mailing lists

The following mailing lists are available:

* http://www.mail-archive.com/user@cassandra.apache.org/[Users]:
General discussion list for users - link:mail-to:user-subscribe@cassandra.apache.org[Subscribe]
* http://www.mail-archive.com/dev@cassandra.apache.org/[Developers]: 
Development related discussion - link:mail-to:dev-subscribe@cassandra.apache.org[Subscribe]
* http://www.mail-archive.com/commits@cassandra.apache.org/[Commits]: 
Commit notification source repository - link:mail-to:commits-subscribe@cassandra.apache.org[Subscribe]
* http://www.mail-archive.com/client-dev@cassandra.apache.org/[Client Libraries]:  
Discussion related to the development of idiomatic client APIs - link:mail-to:client-dev-subscribe@cassandra.apache.org[Subscribe]

Subscribe by clicking on the Subscribe links above. Follow the instructions 
in the welcome email to confirm your subscription. Make sure to keep the welcome email 
as it contains instructions on how to unsubscribe.

== Slack

To chat with users or developers in real-time, join our rooms on
https://s.apache.org/slack-invite[ASF Slack]:

* `cassandra` - for user questions and general discussions.
* `cassandra-dev` - strictly for questions or discussions related to
Cassandra development.
