= Downloading Cassandra
:page-layout: basic-full


[openblock,arrow py-xlarge]
----
[openblock,inner text-center]
------
[discrete]
== Releases
[openblock, cf release-row text-center]
--------

[openblock, inline100 inline-top]
----------
[discrete]
=== Latest Version
[discrete]
==== Apache Cassandra 5.0
[discrete]
==== Latest release on 2023-12-05
[discrete]
==== Maintained until 5.3.0 release (~July 2026)

[.btn.btn--alt]
https://www.apache.org/dyn/closer.lua/cassandra/5.0-beta1/apache-cassandra-5.0-beta1-bin.tar.gz[5.0-beta1,window=blank]

(https://downloads.apache.org/cassandra/5.0-beta1/apache-cassandra-5.0-beta1-bin.tar.gz.asc[pgp,window=blank], https://downloads.apache.org/cassandra/5.0-beta1/apache-cassandra-5.0-beta1-bin.tar.gz.sha256[sha256,window=blank], https://downloads.apache.org/cassandra/5.0-beta1/apache-cassandra-5.0-beta1-bin.tar.gz.sha512[sha512,window=blank]) +
(https://www.apache.org/dyn/closer.lua/cassandra/5.0-beta1/apache-cassandra-5.0-beta1-src.tar.gz[source,window=blank]: https://downloads.apache.org/cassandra/5.0-beta1/apache-cassandra-5.0-beta1-src.tar.gz.asc[pgp,window=blank], https://downloads.apache.org/cassandra/5.0-beta1/apache-cassandra-5.0-beta1-src.tar.gz.sha256[sha256,window=blank], https://downloads.apache.org/cassandra/5.0-beta1/apache-cassandra-5.0-beta1-src.tar.gz.sha512[sha512,window=blank])
----------

[openblock, inline50 inline-top]
----------
[discrete]
=== Latest GA Version
[discrete]
==== Apache Cassandra 4.1
[discrete]
==== Latest release on 2024-02-14
[discrete]
==== Maintained until 5.2.0 release (~July 2025)

[.btn.btn--alt]
https://www.apache.org/dyn/closer.lua/cassandra/4.1.4/apache-cassandra-4.1.4-bin.tar.gz[4.1.4,window=blank]

(https://downloads.apache.org/cassandra/4.1.4/apache-cassandra-4.1.4-bin.tar.gz.asc[pgp,window=blank], https://downloads.apache.org/cassandra/4.1.4/apache-cassandra-4.1.4-bin.tar.gz.sha256[sha256,window=blank], https://downloads.apache.org/cassandra/4.1.4/apache-cassandra-4.1.4-bin.tar.gz.sha512[sha512,window=blank]) +
(https://www.apache.org/dyn/closer.lua/cassandra/4.1.4/apache-cassandra-4.1.4-src.tar.gz[source,window=blank]: https://downloads.apache.org/cassandra/4.1.4/apache-cassandra-4.1.4-src.tar.gz.asc[pgp,window=blank], https://downloads.apache.org/cassandra/4.1.4/apache-cassandra-4.1.4-src.tar.gz.sha256[sha256,window=blank], https://downloads.apache.org/cassandra/4.1.4/apache-cassandra-4.1.4-src.tar.gz.sha512[sha512,window=blank])
----------

[openblock, inline50 inline-top]
----------
[discrete]
=== Previous Stable Version
[discrete]
==== Apache Cassandra 4.0
[discrete]
==== Latest release on 2024-01-23
[discrete]
==== Maintained until 5.1.0 release (~July 2024)

[.btn.btn--alt]
https://www.apache.org/dyn/closer.lua/cassandra/4.0.12/apache-cassandra-4.0.12-bin.tar.gz[4.0.12,window=blank]

(https://downloads.apache.org/cassandra/4.0.12/apache-cassandra-4.0.12-bin.tar.gz.asc[pgp,window=blank], https://downloads.apache.org/cassandra/4.0.12/apache-cassandra-4.0.12-bin.tar.gz.sha256[sha256,window=blank], https://downloads.apache.org/cassandra/4.0.12/apache-cassandra-4.0.12-bin.tar.gz.sha512[sha512,window=blank]) +
(https://www.apache.org/dyn/closer.lua/cassandra/4.0.12/apache-cassandra-4.0.12-src.tar.gz[source,window=blank]: https://downloads.apache.org/cassandra/4.0.12/apache-cassandra-4.0.12-src.tar.gz.asc[pgp,window=blank], https://downloads.apache.org/cassandra/4.0.12/apache-cassandra-4.0.12-src.tar.gz.sha256[sha256,window=blank], https://downloads.apache.org/cassandra/4.0.12/apache-cassandra-4.0.12-src.tar.gz.sha512[sha512,window=blank])
----------


[openblock, inline100 inline-top]
----------

{empty} +

[discrete]
=== Older Maintained Releases
----------

[openblock, inline50 inline-top]
----------

[discrete]
==== Apache Cassandra 3.11
[discrete]
==== Latest release on 2023-08-20
[discrete]
==== Maintained until 5.0.0 release (Nov-Dec 2023)

[.btn.btn--alt]
https://www.apache.org/dyn/closer.lua/cassandra/3.11.16/apache-cassandra-3.11.16-bin.tar.gz[3.11.16,window=blank]

(https://downloads.apache.org/cassandra/3.11.16/apache-cassandra-3.11.16-bin.tar.gz.asc[pgp,window=blank], https://downloads.apache.org/cassandra/3.11.16/apache-cassandra-3.11.16-bin.tar.gz.sha256[sha256,window=blank], https://downloads.apache.org/cassandra/3.11.16/apache-cassandra-3.11.16-bin.tar.gz.sha512[sha512,window=blank]) +
(https://www.apache.org/dyn/closer.lua/cassandra/3.11.16/apache-cassandra-3.11.16-src.tar.gz[source,window=blank]: https://downloads.apache.org/cassandra/3.11.16/apache-cassandra-3.11.16-bin.tar.gz.asc[pgp,window=blank], https://downloads.apache.org/cassandra/3.11.16/apache-cassandra-3.11.16-bin.tar.gz.sha256[sha256,window=blank], https://downloads.apache.org/cassandra/3.11.16/apache-cassandra-3.11.16-bin.tar.gz.sha512[sha512,window=blank])
----------


[openblock, inline50 inline-top]
----------


[discrete]
==== Apache Cassandra 3.0
[discrete]
==== Latest release on 2024-04-15
[discrete]
==== Maintained until 5.0.0 release (Nov-Dec 2023)

[.btn.btn--alt]
https://www.apache.org/dyn/closer.lua/cassandra/3.0.30/apache-cassandra-3.0.30-bin.tar.gz[3.0.30,window=blank]

(https://downloads.apache.org/cassandra/3.0.30/apache-cassandra-3.0.30-bin.tar.gz.asc[pgp,window=blank], https://downloads.apache.org/cassandra/3.0.30/apache-cassandra-3.0.30-bin.tar.gz.sha256[sha256,window=blank], https://downloads.apache.org/cassandra/3.0.30/apache-cassandra-3.0.30-bin.tar.gz.sha512[sha512,window=blank]) +
(https://www.apache.org/dyn/closer.lua/cassandra/3.0.30/apache-cassandra-3.0.30-src.tar.gz[source,window=blank]: https://downloads.apache.org/cassandra/3.0.30/apache-cassandra-3.0.30-src.tar.gz.asc[pgp,window=blank], https://downloads.apache.org/cassandra/3.0.30/apache-cassandra-3.0.30-src.tar.gz.sha256[sha256,window=blank], https://downloads.apache.org/cassandra/3.0.30/apache-cassandra-3.0.30-src.tar.gz.sha512[sha512,window=blank])
----------

[openblock, inline100 inline-top]
----------

{empty} +

[discrete]
==== Unmaintained older versions of Cassandra are archived https://archive.apache.org/dist/cassandra/[here,window=_blank].
[discrete]
==== CVE fixes may be applied to unmaintained versions as decided on a case-by-case basis.
----------

--------
------
----

// START ARROW
[openblock,grad grad--two white]
----
[openblock,pa-xlarge]
------
------
----
// END ARROW

[openblock,arrow pt-xlarge]
----
[openblock,inner]
------

[CAUTION]
====
image:/assets/img/caution.svg[alt="Caution",width=64,height=64]  Debian and RedHat package repositories have moved!

Debian's `sources.list` and RedHat's `cassandra.repo` files must be updated to point to the new repository URLs (see below).
====

[example]
====

[discrete]
=== Installation from Debian packages

* For the `<release series>` specify the major version number, without dot, and with an appended x.
* The latest `<release series>` is `41x`.
* For older releases, the `<release series>` can be one of `40x`, `311`, `30x`, or `22x`.
* Add the Apache Cassandra repository keys:

[source]
--
curl -o /etc/apt/keyrings/apache-cassandra.asc https://downloads.apache.org/cassandra/KEYS
--

* Add the Apache repository of Cassandra to `/etc/apt/sources.list.d/cassandra.sources.list`, for example for the latest 4.1

[source]
--
echo "deb [signed-by=/etc/apt/keyrings/apache-cassandra.asc] https://debian.cassandra.apache.org 41x main" | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list
--

* Update the repositories:

[source]
--
sudo apt-get update
--

* Install Cassandra:

[source]
--
 sudo apt-get install cassandra
--

* You can start Cassandra with `sudo service cassandra start` and stop it with `sudo service cassandra stop`. However, normally the service will start automatically. For this reason be sure to stop it if you need to make any configuration changes.

* Verify that Cassandra is running by invoking `nodetool status` from the command line.

* The default location of configuration files is `/etc/cassandra`.

* The default location of log and data directories is `/var/log/cassandra/` and `/var/lib/cassandra`.

* Start-up options (heap size, etc) can be configured in `/etc/default/cassandra`.
====
// end example

// start example
[example]
====

[discrete]
=== Installation from RPM packages

* For the `<release series>``` specify the major version number, without dot, and with an appended x.
* The latest `<release series>` is `41x`.
* For older releases, the `<release series>` can be one of `311x`, `30x`, or `22x`.
* (Not all versions of Apache Cassandra are available, since building RPMs is a recent addition to the project.)
* For CentOS 7 and similar (rpm < 4.14), append the `noboolean` repository
* Add the Apache repository of Cassandra to `/etc/yum.repos.d/cassandra.repo`, for example for the latest 4.0 version:


[source]
--
[cassandra]
name=Apache Cassandra
baseurl=https://redhat.cassandra.apache.org/41x/
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://downloads.apache.org/cassandra/KEYS
--

Or for CentOS 7:

[source]
--
[cassandra]
name=Apache Cassandra
baseurl=https://redhat.cassandra.apache.org/41x/noboolean/
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://downloads.apache.org/cassandra/KEYS
--

* Install Cassandra, accepting the gpg key import prompts:

[source]
--
sudo yum install cassandra
--
Start Cassandra (will not start automatically):

[source]
--
service cassandra start
--

Systemd based distributions may require to run `systemctl daemon-reload` once to make Cassandra available as a systemd service. This should happen automatically by running the command above.

Make Cassandra start automatically after reboot:


[source]
--
 chkconfig cassandra on
--
Please note that official RPMs for Apache Cassandra only have been available recently and are not tested thoroughly on all platforms yet. We appreciate your feedback and support and ask you to post details on any issues in the corresponding Jira ticket.

====
// end example

// start example
[example]
====
[discrete]
== Source
Development is done in the Apache Git repository. To check out a copy:

[source]
--
git clone https://gitbox.apache.org/repos/asf/cassandra.git
--
====

------
----
