= Download Cassandra
:url-apache-closer: https://www.apache.org/dyn/closer.lua/cassandra
:url-downloads-cassandra: https://downloads.apache.org/cassandra
:latest-name: 4.0-beta4
:3_11-name: 3.11.9
:3_0-name: 3.0.23
:2_2-name: 2.2.19
:2_1-name: 2.1.22
:latest-date: 2020-12-30
:3_11-date: 2020-11-04
:3_0-date: 2020-11-04
:2_2-date: 2020-11-04
:2_1-date: 2020-08-31


== Latest Beta Version

Download the latest Apache Cassandra 4.0 beta release:
{url-apache-closer}/{latest-name}/apache-cassandra-{latest-name}-bin.tar.gz[{latest-name}]
({url-downloads-cassandra}/{latest-name}/apache-cassandra-{latest-name}-bin.tar.gz.asc[pgp],
{url-downloads-cassandra}/{latest-name}/apache-cassandra-{latest-name}-bin.tar.gz.sha256[sha256] and
{url-downloads-cassandra}/{latest-name}/apache-cassandra-{latest-name}-bin.tar.gz.sha512[sha512]), released on {latest-date}.

== Latest Stable Version

Download the latest Apache Cassandra 3.11 release: {url-apache-closer}/{3_11-name}/apache-cassandra-{3_11-name}-bin.tar.gz[{3_11-name}] ({url-downloads-cassandra}/{3_11-name}/apache-cassandra-{3_11-name}-bin.tar.gz.asc[pgp], {url-downloads-cassandra}/{3_11-name}/apache-cassandra-{3_11-name}-bin.tar.gz.sha256[sha256] and {url-downloads-cassandra}/{3_11-name}/apache-cassandra-{3_11-name}-bin.tar.gz.sha512[sha512]), released on {3_11-date}.

== Older Supported Releases

The following older Cassandra releases are still supported:

* Apache Cassandra 3.0 is supported until *6 months after 4.0 release
(date TBD)*. The latest release is {url-apache-closer}/{3_0-name}/apache-cassandra-{3_0-name}-bin.tar.gz[{3_0-name}] ({url-downloads-cassandra}/{3_0-name}/apache-cassandra-{3_0-name}-bin.tar.gz.asc[pgp], {url-downloads-cassandra}/{3_0-name}/apache-cassandra-{3_0-name}-bin.tar.gz.sha256[sha256] and {url-downloads-cassandra}/{3_0-name}/apache-cassandra-{3_0-name}-bin.tar.gz.sha512[sha512]), released on {3_0-date}.
* Apache Cassandra 2.2 is supported until *4.0 release (date TBD)*. The
latest release is {url-apache-closer}/{2_2-name}/apache-cassandra-{2_2-name}-bin.tar.gz[{2_2-name}] ({url-downloads-cassandra}/{2_2-name}/apache-cassandra-{2_2-name}-bin.tar.gz.asc[pgp], {url-downloads-cassandra}/{2_2-name}/apache-cassandra-{2_2-name}-bin.tar.gz.sha256[sha256] and {url-downloads-cassandra}/{2_2-name}/apache-cassandra-{2_2-name}-bin.tar.gz.sha512[sha512]), released on {2_2-date}.
* Apache Cassandra 2.1 is supported until *4.0 release (date TBD)* with
*critical fixes only*. The latest release is {url-apache-closer}/{2_1-name}/apache-cassandra-{2_1-name}-bin.tar.gz[{2_1-name}] ({url-downloads-cassandra}/{2_1-name}/apache-cassandra-{2_1-name}-bin.tar.gz.asc[pgp], {url-downloads-cassandra}/{2_1-name}/apache-cassandra-{2_1-name}-bin.tar.gz.sha256[sha256] and {url-downloads-cassandra}/{2_1-name}/apache-cassandra-{2_1-name}-bin.tar.gz.sha512[sha512]), released on {2_1-date}.

Older (unsupported) versions of Cassandra are
http://archive.apache.org/dist/cassandra/[archived here].
