= Glossary
:page-layout: basic

include::ROOT:partial$alphabet-nav.adoc[]

== A

Approximate Nearest Neighbor (ANN)::
A machine learning algorithm that locates the most similar vectors to a given item in a dataset.

authentication::
Process of establishing the identity of a user, tool, or application.

authorization::
Process of establishing permissions to database resources through roles.

== B

include::ROOT:partial$alphabet-nav.adoc[]

bloom filter::
An off-heap structure associated with each SSTable that checks if any data for the requested row exists in the SSTable before doing any disk I/O.

bootstrap::
The process by which new nodes join the cluster transparently gathering the data needed from existing nodes.

== C

include::ROOT:partial$alphabet-nav.adoc[]

Cassandra::
Apache Cassandra is a distributed, high-available, eventually consistent NoSQL open-source database.

cluster::
Two or more database instances that exchange messages using the gossip protocol. Another way of thinking of a cluster is as a ring of nodes that holds a database.

[[clustering-columns]]
clustering columns::
The columns that determine the order of rows within a partition.

column::
The smallest increment of data. Contains a name, a value, and a timestamp.

commitlog::
A file to which the database appends changed data for recovery in the event of a hardware failure.

consistency::
The synchronization of data on replicas in a cluster. Consistency is categorized as weak or strong.

consistency level::
A setting that defines a successful write or read by the number of cluster replicas that acknowledge the write or respond to the read request, respectively.

CQL shell::
The Cassandra Query Language shell (cqlsh) utility.

== D

include::ROOT:partial$alphabet-nav.adoc[]

datacenter::
A group of related nodes that are configured together within a cluster for replication and workload segregation purposes. 
Not necessarily a separate location or physical data center. Datacenter names are case-sensitive and cannot be changed.

== E

include::ROOT:partial$alphabet-nav.adoc[]

embeddings::
A mathematical technique in machine learning where complex, high-dimensional data is represented as points in a lower-dimensional space. The process of creating an embedding preserves the relevant properties of the original data, such as distance and similarity, enabling easier computational processing. For instance, words with similar meanings in Natural Language Processing (NLP) can be set close to each other in the reduced space, facilitating their use in machine learning models.

Euclidean distance::
A coordinate geometry non-negative distance metric between two points, quantifying the similarity or dissimilarity between those data points represented as vectors. Use it to compare generated samples to real data points.

eventual consistency::
The database maximizes availability and partition tolerance. The database ensures eventual data consistency by updating all replicas during read operations and periodically checking and updating any replicas not directly accessed. The updating and checking ensures that any query always returns the most recent version of the result set and that all replicas of any given row eventually become completely consistent with each other.

== F

include::ROOT:partial$alphabet-nav.adoc[]

== G

include::ROOT:partial$alphabet-nav.adoc[]

[[gossip]]
A peer-to-peer communication protocol for exchanging location and state information between nodes.

== H

include::ROOT:partial$alphabet-nav.adoc[]

[[hint]]
hint::
One of the three ways, in addition to read-repair and full/incremental anti-entropy repair, that Cassandra implements the eventual consistency guarantee that all updates are eventually received by all replicas.

== I

include::ROOT:partial$alphabet-nav.adoc[]

idempotent::
An operation that can occur multiple times without changing the result, such as performing the same update multiple times without affecting the outcome.

immutable::
Data on a disk that cannot be overwritten.

== J

include::ROOT:partial$alphabet-nav.adoc[]

Jaccard similarity::
A measure of similarity between two sets of features or elements in generated data and real data. The mathematical calculation is the size of the intersection of two sets divided by the size of their union, and ranges from zero (0) to one (1). One (1) indicates identical sets.

== K

include::ROOT:partial$alphabet-nav.adoc[]

keyspace::
A namespace container that defines how data is replicated on nodes in each datacenter.

== L

include::ROOT:partial$alphabet-nav.adoc[]

[[listen-address]]
listen address::
Address or interface to bind to and tell other Cassandra nodes to connect to a node.

== M

include::ROOT:partial$alphabet-nav.adoc[]

machine learning (ML)::
A branch of artificial intelligence (AI) and computer science that uses and develops computer systems capable of learning and adapting without explicit instruction. ML uses algorithms and statistical models to analyze data and identify patterns, make decisions, and improve its system.

memtable::
A database table-specific, in-memory data structure that resembles a write-back cache.

== N

include::ROOT:partial$alphabet-nav.adoc[]

node::
A machine that holds Cassandra replicas.
Each node holds a portion of the whole database.

== O

include::ROOT:partial$alphabet-nav.adoc[]

== P

include::ROOT:partial$alphabet-nav.adoc[]

partition::
A partition is a collection of data addressable by a key. This data resides on one node in a Cassandra cluster. A partition is replicated on as many nodes as the replication factor specifies.

partition index::
A list of primary keys and the start position of data.

[[partition-key]]]
partition key::
A partition keys represents a logical entity which helps a Cassandra cluster know on which node some requested data resides.
The column or columns that determine the partition for a table, and identifies which node a partition will be stored on. 
The partition key is hashed to produce a token, which is used to determine which node the partition will be stored on.

The partition key is the first column declared in the primary key definition. In a compound key, multiple columns can declare the columns that form the primary key.

[[primary-key]]]
primary key::
One or more columns that uniquely identify a row in a table.

== Q

include::ROOT:partial$alphabet-nav.adoc[]

== R

include::ROOT:partial$alphabet-nav.adoc[]

replica::
A copy of a portion of the whole database. Each node holds some replicas.

replication::
The process of creating replicas across nodes in a cluster.

replication factor (RF)::
A scalar value that sets the number of replicas of each partition in a cluster.
For example, and RF=3 means that three nodes hold a replica of each partition.

row::
1) Columns that have the same primary key.
2) A collection of cells per combination of columns in the storage engine.

== S

include::ROOT:partial$alphabet-nav.adoc[]

[[seed-node]]
seed node::
A seed node is used to bootstrap the gossip process for new nodes joining a cluster. 
To learn the topology of the ring, a joining node contacts one of the nodes in the -seeds list in cassandra. yaml. 
The first time you bring up a node in a new cluster, only one node is the seed node.

[[snitch]]
snitch::
The mapping from the IP addresses of nodes to physical and virtual locations, such as racks and data centers. 
There are several types of snitches. The type of snitch affects the request routing mechanism.

[[SSTable]]
SSTable::
An SSTable provides a persistent, ordered immutable map from keys to values, where both keys and values are arbitrary byte strings.

[[static-column]]]
static column::
A column that stores the same information in a column for all rows in a table.

strong consistency::
As a database reads data it performs a read repair before returning results.

superuser::
Superuser is a role attribute that provides root database access. Superusers have all permissions on all objects. Apache Cassandra databases include the superuser role cassandra with password cassandra by default. This account runs queries, including logins, with a consistency level of QUORUM. You should create a superuser for deployments and remove the cassandra role.

== T

include::ROOT:partial$alphabet-nav.adoc[]

table::
A collection of columns ordered by name and fetched by row. A row consists of columns and has a primary key; the first part of the key is a column name. Subsequent parts of a compound key are other column names that define the order of columns in the table.

tombstone::
A marker in a row that indicates a column was deleted. During compaction, marked columns are deleted.

TTL::
Time-to-live (TTL) is an optional expiration date for values that are inserted into a column. 

== U

include::ROOT:partial$alphabet-nav.adoc[]

== V

include::ROOT:partial$alphabet-nav.adoc[]

vector::
An array of floating point type that represents a specific object or entity.

Vector Search::
Reviews data on a database to determine the distance between the vectors. The closer they are, the more similar the data. The more the distance, the less similar the data.

== W

include::ROOT:partial$alphabet-nav.adoc[]

[[x-y-z]]
== X, Y, Z

include::ROOT:partial$alphabet-nav.adoc[]

zombie::
A row or cell that reappears in a database table after deletion. 
This can happen if a node goes down for a long period of time and is then restored without being repaired.
+
Deleted data is not erased from database tables; it is marked with tombstones until compaction. 
The tombstones created on one node must be propagated to the nodes containing the deleted data. 
If one of these nodes goes down before this happens, the node may not receive the most up-to-date tombstones. 
If the node is not repaired before it comes back online, the database finds the non-tombstoned items and propagates them to other nodes as new data.
+
To avoid this problem, run nodetool repair on any restored node before rejoining it to its cluster.