= Resources
:page-layout: resources
:page-role: resources
:description: Your source for community content


////
INSTRUCTIONS
- To create a new resource, copy and paste the markup for a resource card adn replace the title and link.
- Copy from //start card to the closest //end card.  
- Leave a blank line between cards.  
- The resource will show up in the order in which it is arranged in this document.
////

//start card
[openblock,card resource-card text-center shadow relative level-Beginner]
----
[openblock,title mt-medium]
------
[discrete]
=== The Search for a Cloud-Native Database
[openblock, res-tags]
--------
cloud native, db
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://dzone.com/articles/the-search-for-a-cloud-native-database[Go to Resource,window=_blank]
------
----
//end card

//start card
[openblock,card resource-card text-center shadow relative level-Beginner]
----
[openblock,title mt-medium]
------
[discrete]
=== Can Spark Applications Coexist with NoSQL Databases?
[openblock, res-tags]
--------
tips, nosql, spark
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://www.capitalone.com/tech/cloud/4-tips-for-spark-and-nosql/[Go to Resource,window=_blank]
------
----
//end card

//start card
[openblock,card resource-card text-center shadow relative level-Beginner]
----
[openblock,title mt-medium]
------
[discrete]
=== Apache Cassandra Architecture
[openblock, res-tags]
--------
architecture
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://www.youtube.com/watch?v=TLNLNRb0RBk[Go to Resource,window=_blank]
------
----
//end card

//start card
[openblock,card resource-card text-center shadow relative level-Beginner]
----
[openblock,title mt-medium]
------
[discrete]
=== Apache Cassandra Lunch #84: Data & Analytics Platform: Cassandra, Spark, Kafka
[openblock, res-tags]
--------
design, ecosystem
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://www.youtube.com/watch?v=EjRDdXMsQO4[Go to Resource,window=_blank]
------
----
//end card

//start card
[openblock,card resource-card text-center shadow relative level-Beginner]
----
[openblock,title mt-medium]
------
[discrete]
=== Top 50 interview questions and answers of Apache Cassandra
[openblock, res-tags]
--------
top, QA, Q&A, interview
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://www.devopsschool.com/blog/top-50-interview-questions-and-answers-of-apache-cassandra/[Go to Resource,window=_blank]
------
----
//end card

//start card
[openblock,card resource-card text-center shadow relative level-Beginner]
----
[openblock,title mt-medium]
------
[discrete]
=== Installing Apache Cassandra on Ubuntu 20.04
[openblock, res-tags]
--------
Linux, Installation, Ubuntu 20.04, Tutorial
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://linuxhint.com/install_cassandra_on_ubuntu_20-04/[Go to Resource,window=_blank]
------
----
//end card

//start card
[openblock,card resource-card text-center shadow relative level-Intermediate]
----
[openblock,title mt-medium]
------
[discrete]
=== How to run Cassandra and Kubernetes together
[openblock, res-tags]
--------
cass-operator, Cloud-native, Installation, Kubernetes, Tutorial
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://www.infoworld.com/article/3575362/how-to-run-cassandra-and-kubernetes-together.html[Go to Resource,window=_blank]
------
----
//end card

//start card  
[openblock,card resource-card text-center shadow relative level-Intermediate]
----
[openblock,title mt-medium]
------
[discrete]
=== PySpark ETL from MySQL and MongoDB to Cassandra
[openblock, res-tags]
--------
Apache Spark, ELT, PySpark, MongoDB, MySQL,Tutorial
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://medium.com/@zorteran/pyspark-etl-from-mysql-and-mongodb-to-cassandra-964a5effc5e5[Go to Resource,window=_blank]
------
----
//end card

//start card  
[openblock,card resource-card text-center shadow relative level-Beginner]
----
[openblock,title mt-medium]
------
[discrete]
=== Install Apache Cassandra on Ubuntu 18.04.5
[openblock, res-tags]
--------
Installation, Linux, Ubuntu 18.04, Webinar
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://www.youtube.com/watch?v=uieacv57NXg[Go to Resource,window=_blank]
------
----
//end card

//start card  
[openblock,card resource-card text-center shadow relative level-Beginner]
----
[openblock,title mt-medium]
------
[discrete]
=== Intro to Apache Cassandra for Data Engineers
[openblock, res-tags]
--------
Docker, Installation
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://www.confessionsofadataguy.com/intro-to-apache-cassandra-for-data-engineers/[Go to Resource,window=_blank]
------
----
//end card

//start card  
[openblock,card resource-card text-center shadow relative level-Intermediate]
----
[openblock,title mt-medium]
------
[discrete]
=== Ejemplo de Spring Data con Cassandra y Docker
[openblock, res-tags]
--------
Docker, SpringData, Spring Boot, Tutorial
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://refactorizando.com/ejemplo-spring-data-cassandra-docker/[Go to Resource,window=_blank]
------
----
//end card

//start card  
[openblock,card resource-card text-center shadow relative level-Intermediate]
----
[openblock,title mt-medium]
------
[discrete]
=== Apache Cassandra Lunch Online Meetup #26: Cassandra Troubleshooting with Logs
[openblock, res-tags]
--------
Logging, Troubleshooting, Webinar
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://www.youtube.com/watch?v=Pns8o4BbaRE[Go to Resource,window=_blank]
------
----
//end card

//start card  
[openblock,card resource-card text-center shadow relative level-Beginner]
----
[openblock,title mt-medium]
------
[discrete]
=== Building Apache Cassandra 4.0: behind the scenes
[openblock, res-tags]
--------
ApacheCon, Cassandra 4.0, Overview, Webinar
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://www.youtube.com/watch?v=rjCVqjLRALo[Go to Resource,window=_blank]
------
----
//end card

//start card  
[openblock,card resource-card text-center shadow relative level-Beginner]
----
[openblock,title mt-medium]
------
[discrete]
=== Building Netflix’s Distributed Tracing Infrastructure
[openblock, res-tags]
--------
Distributed Tracing, Overview
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://netflixtechblog.com/building-netflixs-distributed-tracing-infrastructure-bb856c319304[Go to Resource,window=_blank]
------
----
//end card

//start card  
[openblock,card resource-card text-center shadow relative level-Beginner]
----
[openblock,title mt-medium]
------
[discrete]
=== How to Install Apache Cassandra on CentOS 8
[openblock, res-tags]
--------
CentOS 8, Installation, Linux, Tutorial
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://www.tecmint.com/install-apache-cassandra-on-centos-8/[Go to Resource,window=_blank]
------
----
//end card

//start card  
[openblock,card resource-card text-center shadow relative level-Intermediate]
----
[openblock,title mt-medium]
------
[discrete]
=== Combine new NoSQL logging and auditing features in Apache Cassandra
[openblock, res-tags]
--------
Auditing, Cassandra 4.0, Logging, Overview, Regulatory Compliance
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://opensource.com/article/20/8/nosql-cassandra[Go to Resource,window=_blank]
------
----
//end card


//start card  
[openblock,card resource-card text-center shadow relative level-Beginner]
----
[openblock,title mt-medium]
------
[discrete]
=== How to backup and restore Apache Cassandra on Kubernetes
[openblock, res-tags]
--------
Backup, Kubernetes, PortWorx, Overview
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://portworx.com/how-to-backup-and-restore-apache-cassandra-on-kubernetes/[Go to Resource,window=_blank]
------
----
//end card

//start card  
[openblock,card resource-card text-center shadow relative level-Beginner]
----
[openblock,title mt-medium]
------
[discrete]
=== Spark + Cassandra Best Practices
[openblock, res-tags]
--------
Best Practice, Apache Spark, Overview
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://blog.pythian.com/spark-cassandra-best-practices/[Go to Resource,window=_blank]
------
----
//end card

//start card  
[openblock,card resource-card text-center shadow relative level-Beginner]
----
[openblock,title mt-medium]
------
[discrete]
=== Apache Cassandra – An Essentials Guide
[openblock, res-tags]
--------
Overview
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://hackernoon.com/apache-cassandra-an-essentials-guide-ku1r3yc9[Go to Resource,window=_blank]
------
----
//end card

//start card  
[openblock,card resource-card text-center shadow relative level-Advanced]
----
[openblock,title mt-medium]
------
[discrete]
=== Cassandra counter columns: nice in theory, hazardous in practice
[openblock, res-tags]
--------
Commentary, Counter Columns
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://www.ably.io/blog/cassandra-counter-columns-nice-in-theory-hazardous-in-practice[Go to Resource,window=_blank]
------
----
//end card

//start card  
[openblock,card resource-card text-center shadow relative level-Beginner]
----
[openblock,title mt-medium]
------
[discrete]
=== Understanding Distributed database/system using Cassandra
[openblock, res-tags]
--------
Distributed Database, Overview
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://medium.com/@sauravbhagat_10426/understanding-distributed-database-system-using-cassandra-42125797909a[Go to Resource,window=_blank]
------
----
//end card

//start card  
[openblock,card resource-card text-center shadow relative level-Intermediate]
----
[openblock,title mt-medium]
------
[discrete]
=== Fullstack Kafka
[openblock, res-tags]
--------
App development, Apache Kafka, Microservices, React, Tutorial
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://levelup.gitconnected.com/fullstack-kafka-e735054adcd6[Go to Resource,window=_blank]
------
----
//end card

//start card  
[openblock,card resource-card text-center shadow relative level-Advanced]
----
[openblock,title mt-medium]
------
[discrete]
=== Impacts of many tables in a Cassandra data model
[openblock, res-tags]
--------
Commentary, Tables
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://thelastpickle.com/blog/2020/11/25/impacts-of-many-tables-on-cassandra.html[Go to Resource,window=_blank]
------
----
//end card

//start card  
[openblock,card resource-card text-center shadow relative level-Intermediate]
----
[openblock,title mt-medium]
------
[discrete]
=== How to deploy Cassandra on Openshift and open it up to remote connections
[openblock, res-tags]
--------
OpenShift, Remote Access, Tutorial
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://sindhumurugavel.medium.com/how-to-deploy-cassandra-on-openshift-and-open-it-up-to-remote-connections-c7783861b868[Go to Resource,window=_blank]
------
----
//end card

//start card  
[openblock,card resource-card text-center shadow relative level-Beginner]
----
[openblock,title mt-medium]
------
[discrete]
=== How to install the Apache Cassandra NoSQL database server on Ubuntu 20.04
[openblock, res-tags]
--------
Linux, Installation, Ubuntu 20.04, Tutorial
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://www.techrepublic.com/article/how-to-install-the-apache-cassandra-nosql-database-server-on-ubuntu-20-04/[Go to Resource,window=_blank]
------
----
//end card

//start card  
[openblock,card resource-card text-center shadow relative level-Beginner]
----
[openblock,title mt-medium]
------
[discrete]
=== Spark + Cassandra, All You Need to Know: Tips and Optimizations
[openblock, res-tags]
--------
Apache Spark, Optimization, Overview
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://itnext.io/spark-cassandra-all-you-need-to-know-tips-and-optimizations-d3810cc0bd4e[Go to Resource,window=_blank]
------
----
//end card

//start card  
[openblock,card resource-card text-center shadow relative level-Intermediate]
----
[openblock,title mt-medium]
------
[discrete]
=== Apache Cassandra Collections and Tombstones
[openblock, res-tags]
--------
Collections, Data type, Overview, Tombstones
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://medium.com/@jeromatron/apache-cassandra-collections-and-tombstones-a45315e97cbc[Go to Resource,window=_blank]
------
----
//end card

//start card  
[openblock,card resource-card text-center shadow relative level-Intermediate]
----
[openblock,title mt-medium]
------
[discrete]
=== Apache Cassandra Deployment on OpenEBS and Monitoring on Kubera
[openblock, res-tags]
--------
Kubera, Kubernetes, Monitoring, OpenEBS, Persistent Volume
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://blog.mayadata.io/apache-cassandra-deployment-on-openebs-and-monitoring-on-kubera[Go to Resource,window=_blank]
------
----
//end card

//start card  
[openblock,card resource-card text-center shadow relative level-Intermediate]
----
[openblock,title mt-medium]
------
[discrete]
=== Cassandra Upgrade in production : Strategies and Best Practices
[openblock, res-tags]
--------
ApacheCon, Best Practice, Overview, Upgrade, Webinar
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://www.youtube.com/watch?v=eTUXQS7RUQw&list=PLU2OcwpQkYCy_awEe5xwlxGTk5UieA37m&index=181[Go to Resource,window=_blank]
------
----
//end card

//start card  
[openblock,card resource-card text-center shadow relative level-Advanced]
----
[openblock,title mt-medium]
------
[discrete]
=== How Netflix Manages Version Upgrades of Cassandra at Scale
[openblock, res-tags]
--------
ApacheCon, Best Practice, Overview, Upgrade, Webinar
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://www.youtube.com/watch?v=8QV2Mc-1s64[Go to Resource,window=_blank]
------
----
//end card

//start card  
[openblock,card resource-card text-center shadow relative level-Intermediate]
----
[openblock,title mt-medium]
------
[discrete]
=== Lucene Based Indexes on Cassandra
[openblock, res-tags]
--------
Lucene Based Indexes, Overview, Webinar
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://www.youtube.com/watch?v=Z0NXWmZAB8s[Go to Resource,window=_blank]
------
----
//end card

//start card  
[openblock,card resource-card text-center shadow relative level-Beginner]
----
[openblock,title mt-medium]
------
[discrete]
=== Start using virtual tables in Apache Cassandra 4.0
[openblock, res-tags]
--------
Cassandra 4.0, Overview, Virtual Tables
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://opensource.com/article/20/10/virtual-tables-apache-cassandra[Go to Resource,window=_blank]
------
----
//end card

//start card  
[openblock,card resource-card text-center shadow relative level-Intermediate]
----
[openblock,title mt-medium]
------
[discrete]
=== Benchmarking Apache Cassandra with Rust
[openblock, res-tags]
--------
Benchmarking, Rust, Tutorial
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://pkolaczk.github.io/benchmarking-cassandra/[Go to Resource,window=_blank]
------
----
//end card

//start card  
[openblock,card resource-card text-center shadow relative level-Beginner]
----
[openblock,title mt-medium]
------
[discrete]
=== Build Fault Tolerant Applications With Cassandra API for Azure Cosmos DB
[openblock, res-tags]
--------
API, Azure CosmosDB, Fault Tolerance, Tutorial
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://dzone.com/articles/build-fault-tolerant-applications-with-cassandra-a[Go to Resource,window=_blank]
------
----
//end card

//start card  
[openblock,card resource-card text-center shadow relative level-Beginner]
----
[openblock,title mt-medium]
------
[discrete]
=== Open Source BI Tools and Cassandra
[openblock, res-tags]
--------
Business Intelligence, Open Source, Overview, SQL
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://blog.anant.us/open-source-bi-tools-and-cassandra/[Go to Resource,window=_blank]
------
----
//end card

//start card  
[openblock,card resource-card text-center shadow relative level-Intermediate]
----
[openblock,title mt-medium]
------
[discrete]
=== Understanding Data Modifications in Cassandra
[openblock, res-tags]
--------
Data Modification, Overview
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://www.red-gate.com/simple-talk/blogs/understanding-data-modifications-in-cassandra/[Go to Resource,window=_blank]
------
----
//end card

//start card  
[openblock,card resource-card text-center shadow relative level-Advanced]
----
[openblock,title mt-medium]
------
[discrete]
=== Migrating Cassandra from one Kubernetes cluster to another without data loss
[openblock, res-tags]
--------
CassKop, Operators, Kubernetes, Migration, Tutorial
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://medium.com/flant-com/migrating-cassandra-between-kubernetes-clusters-ae4ab4ada028[Go to Resource,window=_blank]
------
----
//end card

//start card  
[openblock,card resource-card text-center shadow relative level-Advanced]
----
[openblock,title mt-medium]
------
[discrete]
=== Real-time Stream Analytics and User Scoring Using Apache Druid, Flink & Cassandra at Deep.BI
[openblock, res-tags]
--------
Apache Druid, Apache Fink, Business Intelligence, Overview, Real-Time Stream Analytics
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://www.deep.bi/blog/real-time-stream-analytics-and-user-scoring-using-apache-flink-druid-cassandra-at-deep-bi[Go to Resource,window=_blank]
------
----
//end card

//start card  
[openblock,card resource-card text-center shadow relative level-Intermediate]
----
[openblock,title mt-medium]
------
[discrete]
=== Impacts of many columns in a Cassandra table
[openblock, res-tags]
--------
Columns, Commentary
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://thelastpickle.com/blog/2020/12/17/impacts-of-many-columns-in-cassandra-table.html[Go to Resource,window=_blank]
------
----
//end card


//start card  
[openblock,card resource-card text-center shadow relative level-Intermediate]
----
[openblock,title mt-medium]
------
[discrete]
=== Containerized Cassandra Cluster (CCC)
[openblock, res-tags]
--------
ApacheCon, Development, Docker, Local Testing, Webinar
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://www.youtube.com/watch?v=YuwgoFmc05g&list=PLU2OcwpQkYCy_awEe5xwlxGTk5UieA37m&index=182[Go to Resource,window=_blank]
------
----
//end card


//start card  
[openblock,card resource-card text-center shadow relative level-Beginner]
----
[openblock,title mt-medium]
------
[discrete]
=== Getting Involved with the Apache Cassandra Project
[openblock, res-tags]
--------
Open Source, Community, Overview, Webinar
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://www.youtube.com/watch?v=tvroLAZkwQA&list=PLU2OcwpQkYCy_awEe5xwlxGTk5UieA37m&index=183[Go to Resource,window=_blank]
------
----
//end card


//start card  
[openblock,card resource-card text-center shadow relative level-Intermediate]
----
[openblock,title mt-medium]
------
[discrete]
=== Upgrading Cassandra using Automation, with cstar
[openblock, res-tags]
--------
ApacheCon, Automation, cstar, Upgrade, Webinar
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://www.youtube.com/watch?v=xcX_0UXjEvo&list=PLU2OcwpQkYCy_awEe5xwlxGTk5UieA37m&index=185[Go to Resource,window=_blank]
------
----
//end card


//start card  
[openblock,card resource-card text-center shadow relative level-Advanced]
----
[openblock,title mt-medium]
------
[discrete]
=== Hadoop as a Cassandra SSTables producer
[openblock, res-tags]
--------
ApacheCon, Apache Hadoop, Edge, SSTables, Webinar
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://www.youtube.com/watch?v=K-vT4dHrKCE&list=PLU2OcwpQkYCy_awEe5xwlxGTk5UieA37m&index=186[Go to Resource,window=_blank]
------
----
//end card


//start card  
[openblock,card resource-card text-center shadow relative level-Intermediate]
----
[openblock,title mt-medium]
------
[discrete]
=== Truth Hurts: How to Migrate your Data Model to Apache Cassandra
[openblock, res-tags]
--------
ApacheCon, Common Issues, Data Modelling, Migration, Overview, Webinar
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://www.youtube.com/watch?v=td5QRYOeGag&list=PLU2OcwpQkYCy_awEe5xwlxGTk5UieA37m&index=187[Go to Resource,window=_blank]
------
----
//end card

//start card  
[openblock,card resource-card text-center shadow relative level-Beginner]
----
[openblock,title mt-medium]
------
[discrete]
=== Cassandra.Link: Curated Site with Cassandra Articles, Videos, and News Feed
[openblock, res-tags]
--------
Community
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://cassandra.link/[Go to Resource,window=_blank]
------
----
//end card

//start card  
[openblock,card resource-card text-center shadow relative level-Beginner]
----
[openblock,title mt-medium]
------
[discrete]
=== Apache Cassandra Lunch Youtube Playlist By Anant
[openblock, res-tags]
--------
Community, Webinar
--------
------
[openblock,card-btn]
------
[.btn.btn--alt]
https://youtube.com/playlist?list=PLmZzyjM-vqX6f0WQYhHgIv5K-esMRcbyr[Go to Resource,window=_blank]
------
----
//end card