= Third-party projects
:page-layout: basic

== Third-party projects

=== Cassandra as-a-Service cloud offerings

* https://aiven.io/cassandra[Aiven for Apache Cassandra]: Aiven for
Apache Cassandra is a fully managed NoSQL database, deployable in the
cloud of your choice. Snap it into your existing workflows with the
click of a button, automate away the mundane tasks, and focus on
building your core apps. Now running Cassandra 3.11.
* https://aws.amazon.com/keyspaces/[Amazon Keyspaces (for Apache
Cassandra)]: Scalable, highly available, and managed Apache
Cassandra–compatible database service.
* https://astra.datastax.com[DataStax Astra]: Cloud-native database
as-a-service built on Apache Cassandra™ complete with a free-tier and
CQL, REST and GraphQL APIs for faster development. Deployable in AWS and
GCP.
* https://www.instaclustr.com/solutions/managed-apache-cassandra[Instaclustr
Hosted & Managed Apache Cassandra as a Service]: Instaclustr provides a
fully managed and SOC 2 certified hosted & managed service for Apache
Cassandra® on AWS, Azure, GCP and IBM Cloud.

=== Cassandra installation tools

* https://hub.docker.com/_/cassandra[Docker community Cassandra images]:
Docker images for Apache Cassandra maintained by the Docker community
* https://downloads.datastax.com/#desktop[DataStax Desktop]:
Cross-platform (Windows, MacOSX, Linux) application that allows
developers to quickly explore Apache Cassandra™ with a few clicks on
their laptop, complete with tutorials and walkthroughs.
* https://github.com/thelastpickle/tlp-cluster[The Last Pickle
tlp-cluster]: tlp-cluster, a tool for launching Cassandra clusters in
AWS (DataStax)

=== Cassandra tools

* https://cassandra.link[cassandra.link]: Curated site with tools, along
with https://cassandra.tools[cassandra.tools].
* https://github.com/criteo/cassandra_exporter[Cassandra Prometheus
Exporter]: Standalone application which exports Cassandra metrics
through a prometheus friendly endpoint
* https://downloads.datastax.com/#bulk-loader[DataStax Bulk Loader]:
Easy-to-use command line utility for loading and unloading JSON or CSV
files to/from the database, counting rows in tables and identifying
large partitions.
* https://github.com/datastax/metric-collector-for-apache-cassandra[DataStax
Metrics Collector for Cassandra]: Based on Collectd, aggregates OS and
Cassandra metrics along with diagnostic events to facilitate problem
resolution and remediation
* https://hackolade.com/nosqldb.html#cassandra[Hackolade]: Visual data
modeling tool for Cassandra
* https://github.com/thelastpickle/cassandra-medusa[The Last Pickle
Medusa]: Apache Cassandra Backup and Restore Tool (DataStax)
* https://github.com/thelastpickle/cassandra-reaper[The Last Pickle
Reaper]: Automated repair tool for Apache Cassandra (DataStax)
* https://github.com/thelastpickle/tlp-stress[The Last Pickle Cassandra
stress tool, tlp-stress]: A workload-centric stress tool for Apache
Cassandra. Designed for simplicity, no math degree required. (DataStax)
* https://github.com/nosqlbench/nosqlbench[NoSQLBench]: Pluggable
benchmarking suite for Cassandra and other distributed systems

=== Cassandra Kubernetes operators

* https://github.com/mesosphere/kudo-cassandra-operator[D2iQ Cassandra
Kudo Operator]: The KUDO Cassandra Operator makes it easy to deploy and
manage Apache Cassandra on Kubernetes.
* https://github.com/datastax/cass-operator[DataStax cass-operator]: The
DataStax Kubernetes Operator for Apache Cassandra
* https://github.com/instaclustr/cassandra-operator[Instaclustr
cassandra-operator]: The Cassandra operator manages Cassandra clusters
deployed to Kubernetes and automates tasks related to operating a
Cassandra cluster.
* https://orange-opensource.github.io/casskop/[Orange CassKop]: The
Orange Cassandra operator is a Kubernetes operator to automate
provisioning, management, autoscaling and operations of Apache Cassandra
clusters deployed to K8s.
* https://github.com/sky-uk/cassandra-operator[Sky Cassandra Operator]:
The Sky Cassandra Operator is a Kubernetes operator that manages
Cassandra clusters inside Kubernetes.

=== Cassandra management sidecars

* https://github.com/apache/cassandra-sidecar[Apache Cassandra
cassandra-sidecar]: Sidecar for the highly scalable Apache Cassandra
database, built as part of the Apache Cassandra project.
* https://github.com/datastax/management-api-for-apache-cassandra[DataStax
Management API for Apache Cassandra]: RESTful / Secure Management
Sidecar for Apache Cassandra
* https://github.com/datastax/spring-boot[DataStax Spring Boot]: Spring
Boot extension
* https://github.com/instaclustr/cassandra-sidecar[Instaclustr
cassandra-sidecar]: This repository is home of a sidecar for Apache
Cassandra database. Sidecar is meant to be run alongside of Cassandra
instance and sidecar talks to Cassandra via JMX.

=== Developer Frameworks

* http://r4fek.github.io/django-cassandra-engine/[Django Cassandra
Engine]: Cassandra backend for Django Framework that allows you to use
Cqlengine directly in your project.
* https://express-cassandra.readthedocs.io/en/stable/[Express
Cassandra]: Express-Cassandra is a Cassandra ORM/ODM/OGM for NodeJS with
Elassandra & JanusGraph Support.
* https://quarkus.io/guides/cassandra[Quarkus extension for Apache
Cassandra]: An Apache Cassandra(R) extension for Quarkus. Quarkus is A
Kubernetes Native Java stack tailored for OpenJDK HotSpot and GraalVM,
crafted from the best of breed Java libraries and standards.
* https://spring.io/projects/spring-data-cassandra[Spring Data
Cassandra]: With the power to stay at a high level with annotated POJOs,
or at a low level with high performance data ingestion capabilities, the
Spring Data for Apache Cassandra templates are sure to meet every
application need
* https://www.testcontainers.org/modules/databases/cassandra/[TestContainers]:
Testcontainers is a Java library that supports JUnit tests, providing
lightweight, throwaway instances of common databases, Selenium web
browsers, or anything else that can run in a Docker container.

=== Cassandra connectors

==== Apache Kafka

* https://www.confluent.io/hub/confluentinc/kafka-connect-cassandra[Confluent
Connect Cassandra]: The Confluent Cassandra Sink Connector is used to
move messages from Kafka into Apache Cassandra.
* https://downloads.datastax.com/#akc[DataStax Sink Connector]: The
DataStax Apache Kafka Connector automatically takes records from Kafka
topics and writes them to a DataStax Enterprise or Apache Cassandra™
database. This sink connector is deployed in the Kafka Connect framework
and removes the need to build a custom solution to move data between
these two systems.
* https://github.com/debezium/debezium-incubator/tree/master/debezium-connector-cassandra[Debezium
Source Connector]: This connector is currently in incubating state, and
Cassandra is different from the other Debezium connectors since it is
not implemented on top of the Kafka Connect framework.
* https://docs.lenses.io/connectors/sink/cassandra.html[Lenses Sink
Connector]: The Cassandra Sink allows you to write events from Kafka to
Cassandra. The connector converts the value from the Kafka Connect
SinkRecords to JSON and uses Cassandra’s JSON insert functionality to
insert the rows. The task expects pre-created tables in Cassandra.
* https://docs.lenses.io/connectors/source/cassandra.html[Lenses Source
Connector]: Kafka Connect Cassandra is a Source Connector for reading
data from Cassandra and writing to Kafka.

==== Apache Spark

* https://github.com/datastax/spark-cassandra-connector[DataStax Spark
Cassandra Connector]: This library lets you expose Cassandra tables as
Spark RDDs and Datasets/DataFrames, write Spark RDDs and
Datasets/DataFrames to Cassandra tables, and execute arbitrary CQL
queries in your Spark applications.

==== Apache Flink

* https://ci.apache.org/projects/flink/flink-docs-stable/dev/connectors/cassandra.html[Flink
Sink Connector]: This connector provides sinks that writes data into a
Apache Cassandra database.

==== Apache Pulsar

* https://pulsar.apache.org/docs/en/io-quickstart/#connect-pulsar-to-cassandra[Pulsar
Sink Connector]: The Pulsar Cassandra Sink connector is used to write
messages to a Cassandra Cluster.

==== Professional Support

* https://luna.datastax.com/[DataStax Luna],
https://www.datastax.com/services/support/premium-support[DataStax
Premium Support],
https://www.datastax.com/services/professional-services[DataStax
Professional Services]
* https://www.instaclustr.com/services/[Instacluster]
* https://opencredo.com/about-us/[Open Credo]
