= Kinetic Data
:page-layout: case-study
:page-role: case-study
:description: The Apache Cassandra Community
:keywords: 

image::companies/kinetic_data.svg[Kinetic Data,align="center"]

== Kinetic Data Chooses Apache Cassandra to Deliver Workflow Automation Solution

**Company information**

* Enterprise workflow automation
* 50 employees
* Global 2000 clients and government customers, including the USDA, US Army and Navy, Federal Reserve, Fairfax County Public Schools, Emory Healthcare.

**Benefits**

* Distributed fault tolerance 
* Load balancing
* Data durability through replicas
* Low friction for operations teams

Kinetic Data is a leading provider of enterprise workflow automation software. Its Kinetic Platform combines custom workflow builds and pre-built solutions with a low-code environment that enables tech-savvy ‘smarties’ to automate workflow processes. The platform also features pro-code functionality that allows architects to custom code for ease of digital transformation, helping enterprises extend technology investments and lower costs for their systems at scale.

When it came to developing the Kinetic Platform, John Sundberg, president of Kinetic Data wanted a data management system that was robust and minimized friction when using the product: "Everything we do is focused on helping IT and business professionals, those closest to the problems, build their own solutions to those issues," says Sundberg, and when it came to building its workflow platform, Kinetic decided to build atop of Apache Cassandra.

Ultimately, Apache Cassandra was chosen for its robustness. Features including automatic failover, load balancing, and replication eliminated many headaches for Kinetic Data and its customers. Additionally, Kinetic Data wanted to reduce any friction using its products, and the fact Cassandra is open source was appealing as users would not have to wrestle with licensing concerns.

=== Testimonial quote

"Once it's set up and running it’s hands off. Quite frankly, it's easy from an operations perspective. So our customers, they're using Cassandra, but they don't really realize it. But they do say, ‘it's always up. It's always fast.’ It's all these benefits that you really want the end-user to know about."
-- John Sundberg, president of Kinetic Data

=== Performant at scale

Previously, Sundberg had experienced a low-code system that used SQL Server underneath, which highlighted a key challenge: Low-code systems have to be capable of handling the unknown plans of users and how their plans are likely to scale. Normally, a system architect builds a tech stack for a specific use case, understanding the performance requirements and potential bottlenecks. A low-code system, in contrast, provides a framework for someone else to build what they like.

=== Optimized queries

No matter what is being built, Kinetic Data has to guarantee excellent performance. In the past, users would build up a form, and performance would be as they expected initially but as records increased from 5,000 to 50,000 or 500,000 records, users would see a performance drop. Essentially, this is because SQL will accept and execute an inefficient query and take as long as needed to return the result. In contrast, Apache Cassandra would refuse such a query, which meant users would find a problem at record one not record 500,000. Kinetic Data found that, in the development stage, Apache Cassandra guides the user to create efficient queries. 

=== Fault-tolerant and scalable

“I did not want the environment to be a fear,” says Sundberg. “I wanted users to be able to say to themselves, ‘I want to create a form this way’ and be able to go and create it, and when they submitted a form we needed it to fire in the way they wanted.” Kinetic Data found that SQL wasn’t enabling them to eliminate the thought process around the database. “A lot of database talk would pop up when building forms and workflows,” says Sundberg, where they would need to consider creating an index, for instance, in certain situations. This was enabling the hardcore, computer people, but it didn’t enable Kinetic Data to abstract away those issues and empower the subject matter experts to create forms. By choosing Apache Cassandra, a database that was resilient and powerful, Sundberg says “users didn’t have to talk about the database, quite frankly.”

This has enabled the Kinetic platform, to benefit one of the largest healthcare organizations in the Southeast US as a self-service portal to reduce the workload for the IT team. In 2021, the portal was able to track and handle 120,000 tickets and 40,000 incidents quickly, directing the relevant task to the right individual or internal team. In another example, the Technology division for Anne Arundel County Public Schools has been able to manage and track the workflows for 180,000 Chromebooks that are handed out to students. This IT team also manages and tracks all the devices used by 12,000 teachers.

As Kinetic Data abstracts away the complex infrastructure, customers don’t realize they are using Apache Cassandra, but “they do know it’s always up; it’s always fast, and it’s all these benefits you want the end-user to know about,” says Sundberg.

=== About Kinetic Data

Founded in 1998 and headquartered in St. Paul, Minnesota, Kinetic Data is an enterprise software company with its workflow platform that connects human and technology interactions across systems of record at scale. Built on the core tenets of security, scalability, flexibility, and safety, Enterprise organizations are empowered to transform their entire organization with highly efficient, automated workflows that reduces labor cost, cost of service delivery, and risk.