= Liquibase
:page-layout: case-study
:page-role: case-study
:description: Liquibase case study, now supports Cassandra 4.0
:keywords: 

image::companies/liquibase.svg[Liquibase,align="center"]

== Liquibase is Ready to Support Cassandra 4.0 Users 

**Partner information**

* Database Change Management Solution
* Over 75 million downloads of open source Liquibase
* Active in 139 countries
* 1,200+ open source contributors

**Benefits**

* Scalable read and write throughput
* Global resiliency

Liquibase is both an https://www.liquibase.org[open-source database change management tool^], licensed under Apache 2.0, and https://www.liquibase.com[the name of the company^]. While the open source project celebrates over 15 years and 68 releases and over 10,815 commits, commercially the company has the vision to be the easiest, safest, and most powerful community-led database change management solution designed for high-speed CI/CD.

Manual database changes slow the ability to deliver and teams’ ability to collaborate. Every manual review and validation of every database change in every script costs organizations precious time and money. Meanwhile, bad schema changes still sneak through to production—jeopardizing application uptime and putting data at risk of theft. Liquibase solves the important but time-intensive task of database schema updates. By automating the process and eliminating time-consuming back-and-forths between developers and DBAs, Liquibase makes databases safer, easily auditable, and compliant. Originally started in 2006 as an open source project, it continues to be available as both open source and paid-for versions.

=== Testimonial quote

"We hear our customers say all the time that there is no platform that can take all that data as well as Apache Cassandra. If you’re generating tons of data, you need global resiliency; you are going to pick Cassandra. When you need to scale, it does that."
-- Robert Reeves, CTO at Liquibase

While the industry has figured out how to automate application releases, automating database updates has been more challenging, says Robert Reeves, CTO of Liquibase: “We have not figured out how to apply agile, devops, CI/CD, cloud native, and microservices to this database problem. And, it’s just getting worse. The bottleneck is the databases. Liquibase solves this.” But, as companies are generating more data than ever before, databases have had to mature to handle the capacity. Apache Cassandra is one of the databases that Liquibase works with. 

“We hear our customers say all the time that there is no platform that can take all that data as well as Apache Cassandra. If you’re generating tons of data, you need global resiliency; you are going to pick Cassandra. When you need to scale, it does that,” says Reeves.

=== Working at scale with Cassandra 4.0

Liquibase supports Cassandra 3.11 and has added Cassandra 4.0. The company uses the Liquibase Test Harness to utilize existing test cases against new products. Having run 3.11 against 4.0, Liquibase has verified that when customers decide to move, the same set of tools it uses with 3.11 will work with 4.0: “Consumers and customers have a sense of immediacy.” says Reeves. “We have to be ready ahead of time before they move. And, if our customers are using Cassandra, we know that they’re generating a lot of data and that speed is important to them. We’ve verified that Liquibase is going to work when they move to 4.0,” says Reeves. “That’s assuring.” 

Liquibase also highly recommends Apache Cassandra for customers that generate large volumes of data, or who anticipate doing so: “That’s the valuable thing people need to understand about Cassandra. At some point, you’re going to have a ton of data, and if you think you are, you might as well set yourself up right from the beginning,” says Reeves.

=== About Liquibase

Liquibase, the company behind the most powerful open source database change management solution, helps teams release software faster and safer by bringing database changes into existing CI/CD automation. Without automation, CI/CD fails at the database.

By using a repeatable process to easily create, validate, trace, and audit database changes from development through production, teams reduce security risks and costly errors. 

The Liquibase open source project began in 2006 and has over 75 million downloads.