= Events Approval Checklist
:page-layout: basic
:page-role: event-approval-checklist
:description: Checklist for getting your Apache Cassandra® event approved by the PMC

All Apache Cassandra® events must be approved by the Cassandra PMC. To obtain approval, make sure you have familiarized yourself with the https://apache.org/foundation/marks/events.html[Third-Party Event Branding Policy^] and the https://apache.org/foundation/marks/guide[Apache Product Name Usage Guide^], and provided all the details in the checklist below to the PMC via email at mailto:private@cassandra.apache.org[private@cassandra.apache.org^].

_The Apache Cassandra PMC reserves the right to withdraw event approval under reasonable circumstances._

**Format & content**

* Provide details on the format of the event (number of tracks, length of talks, types of talks, etc.)
* Outline the agenda
* Include representatives from the https://cassandra.apache.org/_/community.html#meet-the-community[PMC] on your selection team
* Provide details on how you will be selecting speakers

**Trademark Compliance**

* Highlight how Apache and third-party products are being covered in the content - an event about an Apache product must include some sessions and lessons that can apply to the core download without needing third-party products
* Include and provide details of the event's anti-harassment policy - this must be identical to the https://apache.org/foundation/policies/anti-harassment.html[ASF anti-harassment policy^] or an approved alternative.
* Feature prominent attributions of all Apache marks and products used
* Link the text “Apache Software Foundation” to http://www.apache.org
* The first use of Apache Cassandra must use the full product name and be followed by the ® symbol. The same applies to any usage of the product name in page titles or email subjects.
* Include a prominent description of the appropriate Apache product
* Review and comply with the https://apache.org/foundation/marks/events.html[Third-Party Event Branding Policy^]
* Review and comply with the https://apache.org/foundation/marks/guide[Apache Product Name Usage Guide^]
* Do not include any Apache or Apache product branding directly in your event branding

**Email template**

You can use this as a template for writing an email to the PMC for event approval:

—

I would like to kindly request the PMC's approval for my upcoming {In-Person|Online} event.

My event, {EVENT NAME}, is set to take place on {DATE}. It will be focused on Apache Cassandra and will take the following format:

{Briefly explain the event format - include things like the number of tracks, length of the talks, types of talks, and whether the event will be online or in-person}

The event {Landing/Registration} page is visible at the following URL: {EVENT URL}

Here is an outline of the agenda that we are expecting to follow:

{Provide as much detail about the agenda as you have at this stage - make sure to highlight how you will be covering Apache products in your content}

We will be selecting speakers in the following manner:

{Provide details of your CFP and any processes you plan on implementing for speaker selection, indicating who will be involved in selecting speakers}

We will abide by all Apache trademark and branding guidelines and will include the ASF anti-harassment policy in our event materials.

—