= Meetup Organizer Handbook
:page-layout: basic
:page-role: meetup organizer handbook
:description: Your handbook for organizing a local Apache Cassandra meetup.

Organising events for your local Apache Cassandra® meetup is a rewarding experience and a great way of giving back to your local community while enhancing your own learning. Anyone can organise local Cassandra events so long as they are familiar with using Cassandra and follow these guidelines.

=== The Prime Directive

The overarching principle that informs these guidelines is simple: **Community events are all about the Cassandra community**. This is our Prime Directive.

While that may feel obvious to say, it’s an important point that will underpin all of the decisions you will make as an organiser - keep the community at the forefront, and everything else will fall into place.

Three key guidelines emerge from this Prime Directive:

. All actions taken as an event organiser are with the best interest of the community in mind.
* _Example: Speaker spots are not for sale. Sponsors do not automatically get to speak - all speakers are selected based on their experience, the merit of their topic, and the value it will provide to the community._
. Membership in the local meetup group is open to all who wish to join, regardless of ability, skill, financial status or any other criteria.
* _Example: People don’t need any prior knowledge, skills or technology to attend local Cassandra events._
. Local meetup groups allow events to be organised by any reliable/trusted member of the community.
* _Example: If someone in the community expresses an interest in organising events, they should be encouraged and empowered to do so._

=== Become an Organiser

Any community member can organise events for their local Cassandra meetup. Organisers need to have some familiarity with Apache Cassandra, and they need to agree to the guidelines and expectations outlined below. Anyone interested in starting a new local Cassandra meetup group must fill in https://docs.google.com/forms/d/e/1FAIpQLSfFN7n6RI6Oy4CzLD7MpoHatjzeZX-8tEVVeI3ilLyNAHOp3A/viewform[the application form^]. If you are already a member of a local Cassandra meetup group and would like to get involved as an organiser, talk to the current organisers, and they will gladly accept your assistance. Organising team members cannot all be from the same company (see the _Building an Organising Team section below_).

Once your meetup group is live, we will add your group to the Cassandra meetup directory. See the Promoting Events section below for more information about promoting individual events.

=== Organising Cassandra Events in an External Group

If you are an organiser for another meetup group that isn’t exclusively about Cassandra but you are facilitating Cassandra-focused topics, then we would still love to promote your events to the Cassandra community. You can submit event details via https://docs.google.com/forms/d/e/1FAIpQLSeKY6FG27OlcF2jsUxs0-JyxtWWpYOTZnq7-78ZCTzgw-sVgg/viewform[this form^], and we will add them to the central events calendar.

=== Building an Organising Team

A diverse organising team is important for building a diverse and inclusive community; it also helps distribute the work of organising amongst more people. Remember the Prime Directive - Cassandra events are organised for the benefit of the community and not a single person or organisation.

You can find additional organisers for your team in the #cassandra, #cassandra-events, and #cassandra-dev https://the-asf.slack.com/ssb/redirect[ASF slack^] channels, as well as the in Planet Cassandra Discord, by posting on social media, or by asking people you know who are interested in Apache Cassandra.

=== Promoting Events

It is strongly recommended that you finalise your event details (date, venue, speakers, etc.) at least one month before the event. The earlier you can start promoting your event, the better, so it’s best to get those details finalised well in advance.

You can use any platform you like for your group’s local events. If the platform incurs fees, then you should find local sponsors to cover your costs (see the _Finding Sponsors_ section below). You may use any advertising platform or format you like for promoting your event, provided you https://www.apache.org/foundation/marks/guide#naming[use the correct Cassandra and sponsor branding where appropriate^].

Once your event is published on your platform of choice, submit the details via https://docs.google.com/forms/d/e/1FAIpQLSeKY6FG27OlcF2jsUxs0-JyxtWWpYOTZnq7-78ZCTzgw-sVgg/viewform[this form^] to be added to the central Cassandra calendar. If the platform allows for automated posting, then we will look into enabling that so you don’t need to submit each event individually.

=== Selecting Speakers

Anyone can apply to speak at a local Cassandra event. Organisers can publish a formal Call For Papers (CFP) or just make sure the community knows they can reach out to apply at any time. Speakers and topics can be anything relevant to the local community, and organisers can select what they like, so long as it is in the best interests of the community.

After you launch your local meetup group, we will review your first three events before you announce them - that will ensure that the content remains relevant and follows the program’s guidelines. After that, you won’t need to check in with us before announcing any events, but we will continue to support you and answer any questions you may have.

Here are some things to consider when selecting speakers and topics:

* Speaking spots cannot be bought by sponsors under any circumstances - speakers on selected solely on their merit and the value of their content.
* Sessions must never be purely a sales pitch.
* Focus on new content - if something is already published elsewhere, it will be less attractive to community members.
* Favour new speakers where possible - new voices are interesting to listen to, provide new points of view, and facilitate diversity in the community.
* Make an effort to find and encourage speakers from underrepresented groups where possible - diverse viewpoints make everyone richer.
* Speakers don’t have to be active in the local community, and they can be from out-of-town, but familiarity with existing community members generally means they will be more well-received than others.
* Sessions can be presented in any format that is relevant or useful for the topic - we encourage you to be creative and mix up your event formats.
* Slides must use a plain Cassandra deck that doesn’t include excessive vendor info and branding - if you aren’t sure whether slides are appropriate, please contact Planet Cassandra staff to ask about it.

=== Finding Sponsors

If you need a sponsor for your events, any company can come on board as a sponsor for your local Cassandra meetup; however, it is best to select sponsors that offer relevant products or services to Cassandra community members. Sponsors can come on board to cover any financial costs related to your events - venue hire, refreshments, etc. - or they can provide material sponsorship - venue, workshop materials, etc.

In return for sponsorship, sponsors should receive some benefits. Some ideas for this are:

* Promotion in event communications
* Branding posted at the event
* Discount codes for products/services provided to attendees
* Distribution of company swag

Organisers can be creative with the benefits they provide to sponsors, but please bear in mind the following non-negotiable restrictions:

* Speaking spots are not provided to sponsors in return for their sponsorship under any circumstances.
* A list of attendee names or contact details may not be given to sponsors (or anyone else) - aggregate demographic data is fine to share, but specific details about attendees are not.

=== Finding a Venue

Organisers can use any venue that is appropriate for the event and the people attending it. Here are some things to consider when selecting a venue:

* Ensure that the venue has adequate accessibility features for all potential attendees.
* The venue should be able to accommodate the number of expected attendees with seating for everyone, as well as include any features that are required for the format of the event (e.g. desks/tables for workshops that require attendees to use their laptops)
* Avoid venues that could be potentially problematic for some attendees - this could include political or religious venues.

=== Running Online Events

Organisers may choose to run online events. The same guidelines apply to online events as to in-person ones. When selecting a platform to use for online events, ensure you select a platform that has adequate accessibility features for all attendees, as well as any features that the event format requires.

=== Producing Swag

You may produce event or community-related swag for community members, provided it adheres to the https://www.apache.org/foundation/marks/[ASF Trademark Policy^]. You can check with the Apache Cassandra PMC to ensure compliance. This applies to all event materials, e.g. social graphics, flyers, banners, etc. Here are some guidelines to help organisers make good choices:

* Only produce swag that you are certain will be useful to the majority of attendees - conference and event swag is routinely discarded into landfills, so be conscious of the environment when selecting swag. You could even poll your local community on what swag they want in order to ensure real interest in the items.
* If you are producing t-shirts as swag, make sure to select a vendor that provides shirts in fitted and straight cuts from size XS to 5XL - this ensures that you will be able to cater to all members of the community.
* Also, if you are producing t-shirts, experience has shown that people generally don’t want to continue wearing shirts that are covered in sponsor logos. It is better to stick to designs related to Cassandra or the community.

=== Recording Content

Organisers are encouraged to record sessions at their local Cassandra meetups and publish the recordings online, either as audio or video (or both). All recorded content is licensed under the https://creativecommons.org/licenses/by-sa/4.0/[Creative Commons Attribution-ShareAlike 4.0 License^] - in practice, this means that anyone can redistribute the content, provided they provide attribution to the Cassandra community, use the same licence (and link to it), and indicate any changes they may have made.

== Code of Conduct

The Apache Software Foundation code of conduct applies to all Cassandra community spaces, including events: https://www.apache.org/foundation/policies/conduct[https://www.apache.org/foundation/policies/conduct^]